---
title: "wild animal model implementation with brms"
author: "Sasha Mikheyev"
date: "9/26/2018"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united 
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MCMCglmm)
library(brms)
library(tidyverse)
```

# MCMCglmm following [tutorial](http://www.wildanimalmodels.org/tiki-index.php?page=The+ecologists+guide+to+the+animal+model&highlight=tutorials#ASReml_R)

```{r cache=TRUE}
Data <- as.data.frame(read.table(file = "./gryphon.txt", header = TRUE))
names(Data)[1] <- "animal"
Data$animal <- as.factor(Data$animal)
Data$MOTHER <- as.factor(Data$MOTHER)
Data$BYEAR <- as.factor(Data$BYEAR)
Data$SEX <- as.factor(Data$SEX)
Data$BWT <- as.numeric(Data$BWT)
Data$TARSUS <- as.numeric(Data$TARSUS)
head(Data)

Ped <- as.data.frame(read.table(file = "./gryphonped.txt", header = TRUE))
for (x in 1:3) Ped[, x] <- as.factor(Ped[, x])
head(Ped)

prior1.1 <- list(G = list(G1 = list(V = 1, nu = 0.002)), R = list(V = 1, nu = 0.002))

model1.1 <- MCMCglmm(BWT ~ 1, random = ~animal, pedigree = Ped, data = Data, prior = prior1.1)
summary(model1.1)
plot(model1.1)
posterior.mode(model1.1$VCV)

prior2.1 <- list(G = list(G1 = list(V = diag(2), n = 1.002)),
R = list(V = diag(2), n = 1.002))
model2.1 <- MCMCglmm(cbind(BWT, TARSUS) ~ trait - 1, random = ~us(trait):animal,
rcov = ~us(trait):units, family = c("gaussian", "gaussian"),
pedigree = Ped, data = Data, prior = prior2.1)
summary(model2.1)
plot(model2.1)
```

# brms, following [vignette](https://cran.r-project.org/web/packages/brms/vignettes/brms_phylogenetics.html)

```{r cache=TRUE}
inv.phylo <- MCMCglmm::inverseA(Ped)
A <- solve(inv.phylo$Ainv)
rownames(A) <- rownames(inv.phylo$Ainv)

model_simple1.1 <- brm(
  BWT ~ 1 + (1|animal), data = Data, 
  family = gaussian(), cov_ranef = list(animal = A),
  chains = 2, cores = 2, iter = 1000
)

summary(model_simple1.1)
plot(model_simple1.1)

```

Bivariate model

```{r cache = TRUE}
model_simple2.1 <- brm(
  cbind(BWT, TARSUS) ~ 1 + (1|animal), data = Data, 
  family = gaussian(), cov_ranef = list(animal = A),
  chains = 2, cores = 2, iter = 1000
)
summary(model_simple2.1)
plot(model_simple2.1)
VarCorr(model_simple2.1)
```
