# Introduction {#intro}

The book is provides a series of tutorials (and accompanying data files) to fit animal model in `R` using different packages (`ASReml-R`, `gremlin`, `MCMCglmm` and `brms`) .
You will need to carefully follow the instructions below to download the data files and install the R packages.
Before beginning the tutorial, we assume the reader has successfully installed the chosen R package on their computer and has saved the required data files to an appropriate directory from which they will be read.
Full instructions for how to do this are provided with software distributions.

To work though the different tutorial I would recommend to create a folder where you will save your different `R` scripts for the tutorials. In addition, I recommand to create a subfolder `data` to save the files needed.

## Data

### Data files

 You will need to download 3 data files for the tutorial in `R`:

- gryphon.csv: data on gryphon birth weight
- gryphonRM.csv: data
- gryphonped.csv

In addition, some models presented in the tutorials can take a while to run (sometimes > 1 hour), thus we are also providing model the model outputs to allow you continue the tutorial without waiting for the model to run.

The files are available [here](https://github.com/JulienGAMartin/wam_tuto/tree/master/data)

I recommend to save the data and Rdata files in a subfolder `data` in the folder you will use as your working directory for R and where you will save your R scripts. It should be noted that the tutorial are using this structure to read or save data.


### Notes on data and pedigree

It is always important to take time to think carefully about the strengths and potential limitations of your pedigree information before embarking on quantitative genetic analyses. Pedigree Viewer, written by Brian Kinghorn, is an extremely useful application for visualising pedigrees, and can be downloaded from: http://www-personal.une.edu.au/~bkinghor/pedigree.htm. `Pedantics` an R package written by Michael Morrissey and distributed through CRAN (http://cran.r-project.org/) can also be used for this and offers some nice additional features for visualising pedigree structures and generating associated statistics. Before you begin running through the tutorials, we advise taking a moment to look at the pedigree files provided with them using Pedigree Viewer or Pedantics.

## R

You should check that you have the most current version of R and R packages. You can check the number of the current version on CRAN. If you need to update (or install) R packages, use `install.packages()` and follow the prompted instructions.

### R packages


#### asreml-r

ASReml-R is commercial software published by VSN international (http://www.vsni.co.uk/software/asreml/). This package is not free and requires a key access (add the price of it!)  

#### gremlin

`gremlin` is a little monster appearing if you wet a mugwai and feed it after midnight. It is also a great and promising software to fit mixed models using a frequentist approach.

#### MCMCglmm

`MCMCglmm` is an R package for Bayesian mixed model analysis written by Jarrod Hadfield. It is
freeware distributed through CRAN (http://cran.r-project.org/). Information about the package, together
with a user manual and vignettes are available at http://cran.r-project.org/web/packages/MCMCglmm/index.html .
Reference: [@MCMCglmm2010, @R-MCMCglmm].

This module provides some information that applies to MCMCglmm-based analyses in general, but that will not be included in other tutorials.
Most importantly, this applies to some of the simplest waysof determining the performance of a run using MCMCglmm, i.e., verification of the validity of of the posterior distribution.
This tutorial is not a substitute for working through the MCMCglmm course notes, which is available from CRAN (the Comprehensive R ArchiveNetwork, http://cran.r-project.org/, or can be accessed in R using the command vignette("CourseNotes","MCMCglmm")).
These tutorials do not introduce one of the main advantages of using MCMCglmm for analyses of data from natural populations -the ability to properly model non-normal responses.
These capabilities are introduced inthe documentation that is distributed with MCMCglmm, and available from CRAN.
<!-- i think we have to also cite Pierre de Villemereuil, he wrote a guide for estiamte heritability with MCMCglmmm  http://devillemereuil.legtux.org/wp-content/uploads/2012/12/tuto_en.pdf -->

#### brms

`brms` provides an interface to fit Bayesian generalized multivariate (non-)linear multilevel models using `Stan`, which is a C++ package for obtaining full Bayesian inference (see https://mc-stan.org/).
The formula syntax is an extended version of the syntax applied in the ‘lme4’ package to provide a familiar and simple interface for performing regression analyses.

It should be noted that if `brms` is able to fit animal model the parametrization used based on Kroeneker products is not the most efficient and can take quite longer than using a DAG parametrisation directly in `stan`.
