

<!--
################################################################################
################################################################################
################################################################################
-->


## gremlin


<!--
################################################################################
################################################################################
################################################################################
-->


## MCMCglmm

## Fitting the model

Fitting a multivariate model in MCMCglmm involves several new consideration above those
for fitting univariate models. First, we have to fit multivariate priors; second, we have to
specify the ways in which effects on different traits may covary, including the nature of
residual (co)variation; and third, we will have to be a little more specific when specifying
to MCMCglmm what type of distributions from which we assume our data are drawn.
Our most basic model can be specified as:
> prior2.1 <- list(G = list(G1 = list(V = diag(2), n = 1.002)),
+
R = list(V = diag(2), n = 1.002))
> model2.1 <- MCMCglmm(cbind(BWT, TARSUS) ~ trait - 1, random = ~us(trait):animal,
+
rcov = ~us(trait):units, family = c("gaussian", "gaussian"),
+
pedigree = Ped, data = Data, prior = prior2.1, verbose = FALSE)
> plot(model2.1$VCV[, "TARSUS:TARSUS.animal"])

We have constructed the prior similarly to the those in the univariate models in tutorial
1, only we are specifying a 2x2 covariance matrix rather than a single variance. In order
to provide proper priors, we have set the degree of belief parameter to greater than 1
(1.002). We have used the R command cbind, ‘column-bind’, to specify the two response
variables, body weight and tarsus length. The nature of genetic and residual (co)variance
(between and) of the traits is specified as unstructured matrices, the most general structure
available for this type of data. Finally, we have specified that we wish to treat both traits
as gaussian responses.
In tutorial 1, we used full autocorrelation tables to evaluate the validity of the posterior
distribution. Note that we have not done this here. For a bivariate model this table can
become very complex. Nonetheless, it is worth evaluating, rather it is simply to large
to include here. It can be viewed in the console as before. Here we have displayed only
the autocorrelation for estimates of additive genetic effects for tarsus length with a lag
of five samples (50 iterations given this MCMCglmm run with default values). This lag
of 0.4766 is clearly unacceptable. The posterior distribution of the additive genetic effect
on tarsus length is shown in Figure 4 (p. 15), note the autocorrelation evident in the
left-hand plot. We will opt to run the analysis for longer. This longer run could be run
using the following code:
model2.1<-MCMCglmm(cbind(BWT,TARSUS)~trait-1,
random=~us(trait):animal,
rcov=~us(trait):units,
family=c("gaussian","gaussian"),
pedigree=Ped,data=Data,
nitt=130000,thin=100,burnin=30000,

Density of var1
0.08
Trace of var1
4000
8000
12000Iterations
10 15 20 25
N = 1000 Bandwidth = 0.8424
Figure 4: The posterior distribution of the additive genetic effect for tarsus length in a MCMCglmm run
with default values.

prior=prior2.1,verbose=FALSE)
# the autocorrelation of the genetic variance of TARSUS at Lag 5
autocorr(model2.2$VCV)[,,"TARSUS:TARSUS.animal"][3,4]
However, this run might take as long as an hour. For the purpose of this tutorial we
have provided an output for such a run. It can be obtained and manipulated as follows,
assuming that the file ./model1point1LongRun.Rdat is available at the specified location:
> load(file = "./model2point1LongRun.Rdat")
> autocorr(model2.1$VCV)[, , "TARSUS:TARSUS.animal"][3, 4]
[1] -0.05055322
This level of autocorrelation is more acceptable, at least for the purpose of demonstra-
tion in this tutorial.
We can recover variance components, heritabilities, and genetic correlations from the
posterior distribution of this model:
> posterior.mode(model2.1$VCV)
BWT:BWT.animal
3.143249
TARSUS:TARSUS.animal
11.385778
BWT:TARSUS.units
3.379059
TARSUS:BWT.animal
1.669598
BWT:BWT.units
3.795060
TARSUS:TARSUS.units
17.583740
BWT:TARSUS.animal
1.669598
TARSUS:BWT.units
3.379059
> heritability.BWT2.1 <- model2.1$VCV[, "BWT:BWT.animal"]/(model2.1$VCV[,
+
"BWT:BWT.animal"] + model2.1$VCV[, "BWT:BWT.animal"])
> posterior.mode(heritability.BWT2.1)
var1
0.4999336
> heritability.TARSUS2.1 <- model2.1$VCV[, "TARSUS:TARSUS.animal"]/(model2.1$VCV[,
+
"TARSUS:TARSUS.animal"] + model2.1$VCV[, "TARSUS:TARSUS.units"])
> posterior.mode(heritability.TARSUS2.1)
var1
0.3736259
> genetic.correlation2.1 <- model2.1$VCV[, "BWT:TARSUS.animal"]/sqrt(model2.1$VCV[,
+
"BWT:BWT.animal"] * model2.1$VCV[, "TARSUS:TARSUS.animal"])
> posterior.mode(genetic.correlation2.1)
var1
0.4459136

## Adding fixed and random effects
Fixed and random effects can be added just as for the univariate case. Given that our full
model of BWT from tutorial 1 had SEX as a fixed effect as well as random effects of BYEAR
and MOTHER we could specify a bivariate formulation of this using the following code:
prior2.2<-list(G=list(G1=list(V=diag(2),n=1.002),
G2=list(V=diag(2),n=1.002),
G3=list(VV=diag(2),n=1.002)),
R=list(V=diag(2),n=1.002))
model2.2<-MCMCglmm(cbind(BWT,TARSUS)~trait-1+trait:SEX,
random=~us(trait):animal+us(trait):BYEAR+us(trait):MOTHER,
rcov=~us(trait):units,
family=c("gaussian","gaussian"),
pedigree=Ped,data=Data,
nitt=130000,thin=100,burnin=30000,
prior=prior2.2,verbose=FALSE)
Again we have provided the data from one such run. It can be accessed using the code:
> load(file = "./model2point2LongRun.Rdat")
> autocorr(model2.2$VCV)[, , "TARSUS:TARSUS.animal"][3, 4]
[1] 0.2077895
As before we can obtain the raw variance component estimates and genetic correlations
for the random effects:
> posterior.mode(model2.2$VCV)
BWT:BWT.animal
2.0088157
TARSUS:TARSUS.animal
9.1606591
BWT:TARSUS.BYEAR
0.1691856
TARSUS:BWT.MOTHER
-1.6707200
BWT:BWT.units
1.9438372
TARSUS:TARSUS.units
12.5577406
TARSUS:BWT.animal
BWT:TARSUS.animal
3.2313124
3.2313124
BWT:BWT.BYEAR
TARSUS:BWT.BYEAR
0.9650715
0.1691856
TARSUS:TARSUS.BYEAR
BWT:BWT.MOTHER
3.3479639
1.2381531
BWT:TARSUS.MOTHER TARSUS:TARSUS.MOTHER
-1.6707200
4.4624268
TARSUS:BWT.units
BWT:TARSUS.units
4.1659234
4.1659234
> genetic.correlation2.2 <- model2.2$VCV[, "BWT:TARSUS.animal"]/sqrt(model2.2$VCV[,
+
"BWT:BWT.animal"] * model2.2$VCV[, "TARSUS:TARSUS.animal"])
> maternal.correlation2.2 <- model2.2$VCV[, "BWT:TARSUS.MOTHER"]/sqrt(model2.2$VCV[,
+
"BWT:BWT.MOTHER"] * model2.2$VCV[, "TARSUS:TARSUS.MOTHER"])
> posterior.mode(genetic.correlation2.2)
var1
0.743332

> posterior.mode(maternal.correlation2.2)
var1
-0.8039171
Evaluation of the statistical support for these genetic and maternal correlations is
straightforward. Because we imposed no constraint on their estimation, we can evaluate
the extent to which the posterior distributions overlap zero:
> HPDinterval(genetic.correlation2.2, 0.95)
lower
upper
var1 0.5159636 0.9263339
attr(,"Probability")
[1] 0.95
> HPDinterval(maternal.correlation2.2, 0.95)
lower
upper
var1 -0.9446212 -0.3595398
attr(,"Probability")
[1] 0.95
Neither or these posterior distributions overlapps zero, so we can consider them both
statistically supported.


# Tutorial 3 - A repeated measures animal model

This tutorial will demonstrate how to run a univariate animal model for a trait with
repeated observations using the software MCMCglmm and example data files provided.

## Scenario
Since gryphons are iteroparous, multiple observations of reproductive traits are available
for some individuals. Here we have repeated measures of lay date (measured in days after
Jan 1) for individual females of varying age from 2 (age of maturation) up until age 6.
Not all females lay every year so the number of observations per female is variable. We
want to know how repeatable the trait is, and (assuming it is repeatable) how heritable
it is.

## Data

We use for these examples the same pedigree as was used for tutorials 1 and 2, and we
assume that it is still loaded. If this is not the case, revisit tutorial 1, section 2 for
instructions for loading the pedigree. We are however going to use different phenotypic
data collected from the same population of gryphons, and we need to load these data. We
can load the data from the file gryphonRM.txt into an R data frame using the following
code

>
+
>
>
>
>
>
>
> DataRM <- as.data.frame(read.table(file = "./gryphonRM.txt",
header = TRUE))
names(DataRM)[1] <- "animal"
DataRM$animal <- as.factor(DataRM$animal)
DataRM$BYEAR <- as.factor(DataRM$BYEAR)
DataRM$AGE <- as.factor(DataRM$AGE)
DataRM$YEAR <- as.factor(DataRM$YEAR)
DataRM$LAYDATE <- as.numeric(DataRM$LAYDATE)
head(DataRM)246 animal BYEAR AGE YEAR LAYDATE990
2 992
19990
3 993
23990
4 994
24990
5 995
23990
6 996
29990
2 992> DataRM$ID <- DataRM$animal
> head(DataRM)246
animal BYEAR AGE YEAR LAYDATE ID990
2 992
19 1990
3 993
23 1990
4 994
24 1990
5 995
23 1990
6 996
29 1990
2 992
21 2
Note that we have created a new factor called ID that is the same as the ’animal’
factor. MCMCglmm will recognize the term animal and use it to relate individuals to
their records in a pedigree. The factor ID allows us to disassociate individual records from
the pedigree, which is an important part of analyzing repeated measures data, as we will
see.

## Estimating repeatability

With repeated measures on individuals it is often of interest, prior to fitting a genetic
model, to see how repeatable a trait is. We can estimate the repeatability of a trait as the
proportion of phenotypic variance explained by individual identity using the commands
below
>
>
+
>
+
>
p.var <- var(DataRM$LAYDATE, na.rm = TRUE)
prior3.1 <- list(G = list(G1 = list(V = 1, nu = 0.002)), R = list(V = 1,
nu = 0.002))
model3.1 <- MCMCglmm(LAYDATE ~ 1, random = ~ID, data = DataRM,
prior = prior3.1, verbose = FALSE)
posterior.mode(model3.1$VCV)

ID
units
11.45322 21.14320
Note the use of the new ID factor that we created in the previous section.
Between-individual variance is given by the ID component, while the residual compo-
nent (Variance) therefore represents within-individual variance. Here then the repeata-
bility of the trait can be determined by as 0.353 (i.e., 11.4532/(11.4532+21.1432). Given
that we set up the simulation such that mean lay date changes with age (initially increas-
ing to age 5 before a late life decline) we might ask what the repeatability of lay date is
after conditioning on age effect. This would be done by adding age into the model as a
fixed effect.
>
+
>
>
>
model3.2 <- MCMCglmm(LAYDATE ~ AGE, random = ~ID, data = DataRM,
prior = prior3.1, verbose = FALSE)
plot(model3.2$Sol)
plot(model3.2$VCV)
posterior.mode(model3.2$VCV)
ID
units
12.63794 16.46501
Note that the random effect structure has remained unchaged, and so we have not
modified the prior between models 3.1 and 3.2.
So that the repeatability of laydate, after accounting for age effects, is now estimated
as 0.445 (i.e., 12.6379/(12.6379+16.465). So, just as we saw when estimating h 2 in tutorial
1, the inclusion of fixed effects will alter the estimated effect size if we determine total
phenotypic variance as the sum of the variance components. Thus, proper interpretation
is vital.
Here age is modelled as a 5 level factor (see the convertion of age to a factor in section
3.2). We could equally have fitted it as a continuous variable instead in which case, given
the late life decline, we would probably also include a quadratic term.

## Partitioning additive and permanent environment effects

Generally we expect that the repeatability will set the upper limit for heritability since,
while additive genetic effects will cause among-individual variation, so will other types
of effect. Non-additive contributions to fixed among-individual differences are normally
referred to as ‘permanent environment effects’, although ‘non-heritable effects’ that are
consistent within individuals may be a better way to think of modelling this effect. If a
trait has repeated measures then it is necessary to model permanent environment effects
in an animal model to prevent upward bias in V A . To illustrate this fit the animal model
> model3.3 <- MCMCglmm(LAYDATE ~ 1 + AGE, random = ~animal, pedigree = Ped,
+
data = DataRM, prior = prior3.1, verbose = FALSE)
> posterior.mode(model3.3$VCV)
animal
units
13.67353 16.92081
20


This suggests that all of the among-individual variance is - rightly or wrongly - being
partitioned as V A here. In fact here the partition is wrong since the simulation included
both additive genetic effects and additional fixed heterogeneity that was not associated
with the pedigree structure (i.e. permanent environment effects). An more appropriate
estimate of V A is given by the model:
>
>
+
>
+
>
p.var <- var(DataRM$LAYDATE, na.rm = TRUE)
prior3.4 <- list(G = list(G1 = list(V = 1, n = 0.002), G2 = list(V = 1,
n = 0.002)), R = list(V = 1, n = 0.002))
model3.4 <- MCMCglmm(LAYDATE ~ 1 + AGE, random = ~animal + ID,
pedigree = Ped, data = DataRM, prior = prior3.4, verbose = FALSE)
posterior.mode(model3.4$VCV)
animal
5.123798
ID
units
7.056109 16.242474
The estimate of V A is now much lower (reduced from 13.6735 to 5.1238) since the ad-
ditive and permanent environment effects are being properly separated. We could obtain
estimates of h 2 and of the repeatability from this model using the following commands:
> model3.4.VP <- model3.4$VCV[, "animal"] + model3.4$VCV[, "ID"] +
+
model3.4$VCV[, "units"]
> model3.4.IDplusVA <- model3.4$VCV[, "animal"] + model3.4$VCV[,
+
"ID"]
> posterior.mode(model3.4.IDplusVA/model3.4.VP)
var1
0.4416178
> posterior.mode(model3.4$VCV[, "animal"]/model3.4.VP)
var1
0.1402542

## Adding additional effects and testing significance

Models of repeated measures can be extended to include other fixed or random effects.
For example try including year of measurement (YEAR).
>
>
+
+
>
+
+
>
p.var <- var(DataRM$LAYDATE, na.rm = TRUE)
prior3.5 <- list(G = list(G1 = list(V = 1, n = 0.002), G2 = list(V = 1,
n = 0.002), G3 = list(V = 1, n = 0.002), G4 = list(V = 1,
n = 0.002)), R = list(V = 1, n = 0.002))
model3.5 <- MCMCglmm(LAYDATE ~ 1 + AGE, random = ~animal + ID +
YEAR + BYEAR, pedigree = Ped, data = DataRM, prior = prior3.5,
verbose = FALSE)
posterior.mode(model3.5$VCV)


This model will return additional variance components corresponding to year of mea-
surement effects and birth year (of the female effects). The latter were not simulated as
should be apparent from the parameter estimate (and by the support interval derivable
from the posterior distribution and from DIC-based comparison of model3.5 and a model
from which the birth year term had been eliminated, see tutorial 1). However, YEAR ef-
fects were simulated as should be apparent from the from the modal estimate and from
the support interval (try this yourself using HPDinterval()) and this could be formally
confirmed by comparison of DIC.
YEAR effects could alternatively be included as fixed effects (try this, you should be
able to handle the new prior specification at this point). Since we simulated large year
of measurement effects this treatment will reduce V R and increase the the estimates of
heritability and repeatability which must now be interpreted as proportions of phenotypic
variance after conditioning on both age and year of measurement effects.


<!--
################################################################################
################################################################################
################################################################################
-->


## brms

```{r cache = TRUE,eval = FALSE}
library(brms)
Amat <- nadiv::makeA(Ped)
model_simple2.1 <- brm(
  cbind(BWT, TARSUS) ~ 1 + (1|animal), data = Data,
  family = gaussian(), cov_ranef = list(ANIMAL = A),
  chains = 2, cores = 2, iter = 1000
)
summary(model_simple2.1)
plot(model_simple2.1)
VarCorr(model_simple2.1)
```
