project:
  type: book
  resources:
    - .nojekyll
#  pre-render: _move-files.r
  post-render: 
    - _remove-files.r

profile:
  default: en-US
  group: [en, fr, es]

execute: 
  cache: true
  freeze: auto

book:
  google-analytics: G-LLHQEESR2L
  date: today
  date-format: iso 
  reader-mode: true
  search: true
  site-url: https://juliengamartin.github.io/wam_tuto/
  repo-url: https://github.com/juliengamartin/wam_tuto/
  repo-actions: [edit, issue]
  downloads: pdf #[pdf, epub]

bibliography: [biblio/book.bib, biblio/grateful-refs.bib]
biblio-style: apalike
csl: biblio/ecology.csl

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, css/theme-dark.scss]
    css: css/style.css
    code-link: true
    callout-appearance: simple

#  pdf:
#    documentclass: scrbook
#    include-in-header: latex/preamble.tex
#    include-before-body: latex/before_body.tex
#    include-after-body: latex/after_body.tex
#    toc-depth: 2

#  epub:
#    dev: svglite
#    stylesheet: css/epub.css
#    toc: true


