project:
  output-dir: docs/fr

lang: fr-fr

book:
  title: "Comment faire un modèle animal?"
  subtitle: "An ecologist guide"
  description: |
    Tutorial on how to fit an animal model using multiple R packages.
    Updated and extended tutorials from An ecologist guide to animal model [@wilson2010].
  author: 
    - Julien Martin
    - Matthieu Videlier
  page-footer:
    left: |
      By J Martin & M Videlier
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
#  cover-image: images/blue_dragon.jpg
  navbar:
    background: light
    collapse-below: lg
    title: "How to fit an animal model?"
    left:
      - text: Extra resources
        menu:
          - text: WamWiki
            href: https://wildanimalmodels.org/
          - text: Tutorials by P de Vilemereuil
            href: https://devillemereuil.legtux.org/downloads/
    right:
      - icon: flag
        menu:
        - href: ../
          text: English
        - href: ../es/
          text: Espanol

  chapters:
    - index.qmd
    - fr/01_intro.Rmd
    - part: Univariate model
      chapters:
        - fr/02_00-univ.Rmd
        - fr/02_01-univ_asreml.Rmd  
        - fr/02_02-univ_gremlin.Rmd 
#        - fr/02_03-univ_mcmcglmm.Rmd
#        - fr/02_04-univ_brms.Rmd    
#        - fr/02_05-univ_stan.Rmd    
#    - part: Bivariate model
#      chapters:
#        - fr/03_00-biv.Rmd
#        - fr/03_01-biv_asreml.Rmd   
#        - fr/03_02-biv_gremlin.Rmd  
#        - fr/03_03-biv_mcmcglmm.Rmd 
#        - fr/03_04-biv_brms.Rmd     
#        - fr/03_05-biv_stan.Rmd     
#    - part : Model with repeated measures
#      chapters: 
#        - fr/04_00-rep.Rmd         
#        - fr/04_01-rep_asreml.Rmd   
#        - fr/04_02-rep_gremlin.Rmd  
#        - fr/04_03-rep_mcmcglmm.Rmd 
#        - fr/04_04-rep_brms.Rmd     
#        - fr/04_05-rep_stan.Rmd     
#    - fr/05_code_cheatsheet.Rmd
    - fr/98_references.qmd
##  appendices:
##    - fr/99_app_rep-lmer.Rmd


