<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>2.2 Asreml-R | How to fit an animal model</title>
  <meta name="description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="2.2 Asreml-R | How to fit an animal model" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/missing.png" />
  <meta property="og:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="github-repo" content="JulienGAMartin/wam_tuto" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="2.2 Asreml-R | How to fit an animal model" />
  
  <meta name="twitter:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="twitter:image" content="images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scenario-and-data.html"/>
<link rel="next" href="gremlin-1.html"/>
<script src="libs/header-attrs-2.7.3/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">How to fit an animal model</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1.1</b> Data</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data.html"><a href="data.html#data-files"><i class="fa fa-check"></i><b>1.1.1</b> Data files</a></li>
<li class="chapter" data-level="1.1.2" data-path="data.html"><a href="data.html#notes-on-data-and-pedigree"><i class="fa fa-check"></i><b>1.1.2</b> Notes on data and pedigree</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>1.2</b> R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="r.html"><a href="r.html#r-packages"><i class="fa fa-check"></i><b>1.2.1</b> R packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-animal-model.html"><a href="univariate-animal-model.html"><i class="fa fa-check"></i><b>2</b> Univariate animal model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html"><i class="fa fa-check"></i><b>2.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html#scenario"><i class="fa fa-check"></i><b>2.1.1</b> Scenario</a></li>
<li class="chapter" data-level="2.1.2" data-path="scenario-and-data.html"><a href="scenario-and-data.html#data-files-1"><i class="fa fa-check"></i><b>2.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html"><i class="fa fa-check"></i><b>2.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="asreml-r-1.html"><a href="asreml-r-1.html#running-the-model"><i class="fa fa-check"></i><b>2.2.1</b> Running the model</a></li>
<li class="chapter" data-level="2.2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html#estimating-heritability"><i class="fa fa-check"></i><b>2.2.2</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.2.3" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-fixed-effects"><i class="fa fa-check"></i><b>2.2.3</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.2.4" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-random-effects"><i class="fa fa-check"></i><b>2.2.4</b> Adding random effects</a></li>
<li class="chapter" data-level="2.2.5" data-path="asreml-r-1.html"><a href="asreml-r-1.html#testing-significance-of-random-effects"><i class="fa fa-check"></i><b>2.2.5</b> Testing significance of random effects</a></li>
<li class="chapter" data-level="2.2.6" data-path="asreml-r-1.html"><a href="asreml-r-1.html#futher-partitionning-the-variance"><i class="fa fa-check"></i><b>2.2.6</b> Futher partitionning the variance</a></li>
<li class="chapter" data-level="2.2.7" data-path="asreml-r-1.html"><a href="asreml-r-1.html#covariance-between-different-random-effect-and-possible-negative-variance"><i class="fa fa-check"></i><b>2.2.7</b> Covariance between different random effect and possible negative variance</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="gremlin-1.html"><a href="gremlin-1.html"><i class="fa fa-check"></i><b>2.3</b> gremlin</a></li>
<li class="chapter" data-level="2.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html"><i class="fa fa-check"></i><b>2.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#running-the-model-1"><i class="fa fa-check"></i><b>2.4.1</b> Running the model</a></li>
<li class="chapter" data-level="2.4.2" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#estimating-heritability-1"><i class="fa fa-check"></i><b>2.4.2</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.4.3" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-fixed-effects-1"><i class="fa fa-check"></i><b>2.4.3</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.4.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-random-effects-1"><i class="fa fa-check"></i><b>2.4.4</b> Adding random effects</a></li>
<li class="chapter" data-level="2.4.5" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#testing-significance-of-variance-components"><i class="fa fa-check"></i><b>2.4.5</b> Testing significance of variance components</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="brms-1.html"><a href="brms-1.html"><i class="fa fa-check"></i><b>2.5</b> brms</a></li>
<li class="chapter" data-level="2.6" data-path="stan.html"><a href="stan.html"><i class="fa fa-check"></i><b>2.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multivariate-animal-model.html"><a href="multivariate-animal-model.html"><i class="fa fa-check"></i><b>3</b> Multivariate animal model</a>
<ul>
<li class="chapter" data-level="3.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html"><i class="fa fa-check"></i><b>3.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#scenario-1"><i class="fa fa-check"></i><b>3.1.1</b> Scenario</a></li>
<li class="chapter" data-level="3.1.2" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#gryphon-files"><i class="fa fa-check"></i><b>3.1.2</b> gryphon files</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="asreml-biv.html"><a href="asreml-biv.html"><i class="fa fa-check"></i><b>3.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="asreml-biv.html"><a href="asreml-biv.html#running-the-model-2"><i class="fa fa-check"></i><b>3.2.1</b> Running the model</a></li>
<li class="chapter" data-level="3.2.2" data-path="asreml-biv.html"><a href="asreml-biv.html#adding-fixed-and-random-effects"><i class="fa fa-check"></i><b>3.2.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.2.3" data-path="asreml-biv.html"><a href="asreml-biv.html#significance-testing"><i class="fa fa-check"></i><b>3.2.3</b> Significance testing</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="gremlin-2.html"><a href="gremlin-2.html"><i class="fa fa-check"></i><b>3.3</b> gremlin</a></li>
<li class="chapter" data-level="3.4" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html"><i class="fa fa-check"></i><b>3.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#fitting-the-model"><i class="fa fa-check"></i><b>3.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.4.2" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#adding-fixed-and-random-effects-1"><i class="fa fa-check"></i><b>3.4.2</b> Adding fixed and random effects</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="brms-2.html"><a href="brms-2.html"><i class="fa fa-check"></i><b>3.5</b> brms</a></li>
<li class="chapter" data-level="3.6" data-path="stan-1.html"><a href="stan-1.html"><i class="fa fa-check"></i><b>3.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rep-measures.html"><a href="rep-measures.html"><i class="fa fa-check"></i><b>4</b> A repeated measures animal model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html"><i class="fa fa-check"></i><b>4.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#scenario-2"><i class="fa fa-check"></i><b>4.1.1</b> scenario</a></li>
<li class="chapter" data-level="4.1.2" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#data-files-2"><i class="fa fa-check"></i><b>4.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html"><i class="fa fa-check"></i><b>4.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="asreml-r-2.html"><a href="asreml-r-2.html#estimating-repeatability"><i class="fa fa-check"></i><b>4.2.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.2.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html#partitioning-additive-and-permanent-environment-effects"><i class="fa fa-check"></i><b>4.2.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.2.3" data-path="asreml-r-2.html"><a href="asreml-r-2.html#adding-additional-effects-and-testing-significance"><i class="fa fa-check"></i><b>4.2.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="gremlin-3.html"><a href="gremlin-3.html"><i class="fa fa-check"></i><b>4.3</b> gremlin</a></li>
<li class="chapter" data-level="4.4" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html"><i class="fa fa-check"></i><b>4.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#estimating-repeatability-1"><i class="fa fa-check"></i><b>4.4.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.4.2" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#partitioning-additive-and-permanent-environment-effects-1"><i class="fa fa-check"></i><b>4.4.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.4.3" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#adding-additional-effects-and-testing-significance-1"><i class="fa fa-check"></i><b>4.4.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="brms-3.html"><a href="brms-3.html"><i class="fa fa-check"></i><b>4.5</b> brms</a></li>
<li class="chapter" data-level="4.6" data-path="stan-2.html"><a href="stan-2.html"><i class="fa fa-check"></i><b>4.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quick-comparison-of-codes.html"><a href="quick-comparison-of-codes.html"><i class="fa fa-check"></i><b>5</b> Quick comparison of codes</a>
<ul>
<li class="chapter" data-level="5.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html"><i class="fa fa-check"></i><b>5.1</b> Univariate model with repeated measures</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#asreml-r-3"><i class="fa fa-check"></i><b>5.1.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.1.2" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#gremlin-4"><i class="fa fa-check"></i><b>5.1.2</b> gremlin</a></li>
<li class="chapter" data-level="5.1.3" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#mcmcglmm-4"><i class="fa fa-check"></i><b>5.1.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.1.4" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#brms-4"><i class="fa fa-check"></i><b>5.1.4</b> brms</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bivariate-model.html"><a href="bivariate-model.html"><i class="fa fa-check"></i><b>5.2</b> bivariate model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bivariate-model.html"><a href="bivariate-model.html#asreml-r-4"><i class="fa fa-check"></i><b>5.2.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.2.2" data-path="bivariate-model.html"><a href="bivariate-model.html#gremlin-5"><i class="fa fa-check"></i><b>5.2.2</b> gremlin</a></li>
<li class="chapter" data-level="5.2.3" data-path="bivariate-model.html"><a href="bivariate-model.html#mcmcglmm-5"><i class="fa fa-check"></i><b>5.2.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.2.4" data-path="bivariate-model.html"><a href="bivariate-model.html#brms-5"><i class="fa fa-check"></i><b>5.2.4</b> brms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">How to fit an animal model</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="asreml-r-1" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Asreml-R</h2>
<div id="running-the-model" class="section level3" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Running the model</h3>
<p>First we need to load the <code>asreml</code> library:</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="asreml-r-1.html#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(asreml)</span></code></pre></div>
<p>To be able to fit an animal model Asreml-r needs (the inverse of) the relationship matrix:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="asreml-r-1.html#cb5-1" aria-hidden="true" tabindex="-1"></a>ainv <span class="ot">&lt;-</span> <span class="fu">ainverse</span>(gryphonped)</span></code></pre></div>
<p>We are now ready to specify our first model:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="asreml-r-1.html#cb6-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb6-2"><a href="asreml-r-1.html#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span>, <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv),</span>
<span id="cb6-3"><a href="asreml-r-1.html#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb6-4"><a href="asreml-r-1.html#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb6-5"><a href="asreml-r-1.html#cb6-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb6-6"><a href="asreml-r-1.html#cb6-6" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:01 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4128.454           1.0    853 21:27:01    0.0
##  2     -3284.272           1.0    853 21:27:01    0.0
##  3     -2354.992           1.0    853 21:27:01    0.0
##  4     -1710.357           1.0    853 21:27:01    0.0
##  5     -1363.555           1.0    853 21:27:01    0.0
##  6     -1263.516           1.0    853 21:27:01    0.0
##  7     -1247.854           1.0    853 21:27:01    0.0
##  8     -1247.185           1.0    853 21:27:01    0.0
##  9     -1247.183           1.0    853 21:27:01    0.0</code></pre>
<p>In this model, <code>bwt</code> is the response variable and the only fixed effect is the mean (the intercept, denoted as <code>1</code>). The only random effect we have fitted is <code>animal</code>, which will provide an estimate of <span class="math inline">\(V_A\)</span>. Our random <code>animal</code> effect is connected to the inverse related matrix <code>ainv</code>. <code>data=</code> specifies the name of the dataframe that contains our variables. Finally, we tell <code>asreml()</code> what to when it encounters <code>NA</code>s in either the dependent or predictor variables (in this case we choose to remove the records). If you use the argument “include” instead of “omit,” model will keep the NA. With x=“include,” the model will exchange <code>NA</code> with 0. Be careful you need to standardize your trait so the mean will be equal to 0, if not estimates (including covariance in multivaraite models) could be strongly biased due to the the missing values. y=“include” will exchange <code>NA</code> with a factor labelled mv which will be included in the sparse equation. For more details see asreml-R manual.</p>
<p>A note of the specification of the structure of the residuals: This simple univariate model will run fine without <code>residual=~idv(units)</code>. However, if you are going to use <code>vpredict()</code> to calculate the heritability (see below), not specifying the residuals in this way will result in a standard error for the heritability that is incorrect.</p>
<p>Any model has assumption which need to be checked. The model can be plot which help visualizing the distribution of the model residual and check the different assumptions.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="asreml-r-1.html#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model1)</span></code></pre></div>
<p><img src="wam_tuto_files/figure-html/unnamed-chunk-9-1.svg" width="672" /></p>
<p>To see the estimates for the variance components, we run:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="asreml-r-1.html#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model1)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error  z.ratio bound %ch
## vm(animal, ainv)  3.395398 0.6349915 5.347154     P   0
## units!units       3.828602 0.5185919 7.382687     P   0
## units!R           1.000000        NA       NA     F   0</code></pre>
<p>We fitted a single random effect so have partitioned the phenotypic variance into two components. The <code>vm(animal, ainv)</code> variance component is <span class="math inline">\(V_A\)</span> and is estimated as 3.4. Given that the ratio of <span class="math inline">\(V_A\)</span> to its standard error (<code>z.ratio</code>) is considerably larger than 2 (<em>i.e.</em> the parameter estimate is more than 2 SEs from zero) this looks likely to be significant. The <code>units!units</code> component refers to the residual variance <span class="math inline">\(V_R\)</span>, and <code>units$R</code> should be ignored. If you don’t include <code>residual=~idv(units)</code>in your model specification, <code>units$R</code> will provide you with the residual variance.</p>
</div>
<div id="estimating-heritability" class="section level3" number="2.2.2">
<h3><span class="header-section-number">2.2.2</span> Estimating heritability</h3>
<p>We can calculate the <span class="math inline">\(h^2\)</span> of birth weight from the components above since <span class="math inline">\(h^2 = V_A/V_P = V_A/(V_A+V_R)\)</span>. Thus according to this model, <span class="math inline">\(h^2\)</span> = 3.4 / (3.4 + 3.83) = 0.47.</p>
<p>Alternatively we can use the <code>vpredict()</code> function to calculate <span class="math inline">\(h^2\)</span> and its standard error:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="asreml-r-1.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model1, h2.bwt <span class="sc">~</span> V1 <span class="sc">/</span> (V1 <span class="sc">+</span> V2))</span></code></pre></div>
<pre><code>##         Estimate         SE
## h2.bwt 0.4700163 0.07650881</code></pre>
</div>
<div id="adding-fixed-effects" class="section level3" number="2.2.3">
<h3><span class="header-section-number">2.2.3</span> Adding fixed effects</h3>
<p>To add fixed effects to a univariate model simply modify the model statement. For example we might know (or suspect) that birth weight is a sexually dimorphic trait and therefore fit a model</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="asreml-r-1.html#cb13-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb13-2"><a href="asreml-r-1.html#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sex,</span>
<span id="cb13-3"><a href="asreml-r-1.html#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv),</span>
<span id="cb13-4"><a href="asreml-r-1.html#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb13-5"><a href="asreml-r-1.html#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb13-6"><a href="asreml-r-1.html#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb13-7"><a href="asreml-r-1.html#cb13-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:02 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -3364.126           1.0    852 21:27:02    0.0
##  2     -2702.117           1.0    852 21:27:02    0.0
##  3     -1978.916           1.0    852 21:27:02    0.0
##  4     -1487.834           1.0    852 21:27:02    0.0
##  5     -1236.350           1.0    852 21:27:02    0.0
##  6     -1172.771           1.0    852 21:27:02    0.0
##  7     -1165.270           1.0    852 21:27:02    0.0
##  8     -1165.093           1.0    852 21:27:02    0.0
##  9     -1165.093           1.0    852 21:27:02    0.0</code></pre>
<p>Now we can look at the fixed effects parameters and assess their significance with a conditional Wald F-test:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="asreml-r-1.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2, <span class="at">coef =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>coef.fixed</span></code></pre></div>
<pre><code>##             solution std error  z.ratio
## sex_1       0.000000        NA       NA
## sex_2       2.206996 0.1619974 13.62365
## (Intercept) 6.058669 0.1718244 35.26082</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="asreml-r-1.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.asreml</span>(model2, <span class="at">ssType =</span> <span class="st">&quot;conditional&quot;</span>, <span class="at">denDF =</span> <span class="st">&quot;numeric&quot;</span>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:02 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -1165.093           1.0    852 21:27:02    0.0
##  2     -1165.093           1.0    852 21:27:02    0.0
## Calculating denominator DF</code></pre>
<pre><code>## $Wald
## [0;34m
## Wald tests for fixed effects.[0m
## [0;34mResponse: bwt[0m
## 
##             Df denDF  F.inc  F.con Margin          Pr
## (Intercept)  1   251 3491.0 3491.0        0.00000e+00
## sex          1   831  185.6  185.6      A 2.70204e-38
## 
## $stratumVariances
##                         df Variance vm(animal, ainv) units!units
## vm(animal, ainv) 752.28476 5.957254        0.9864077           1
## units!units       99.71524 2.938413        0.0000000           1</code></pre>
<p>The very small probability (<code>Pr</code>) in the Wald test above shows that <code>sex</code> is a highly significant fixed effect, and from the parameter estimates (<code>summary(model2,coef=T)$coef.fixed</code>) we can see that the average male (sex 2) is 2.2 kg (<span class="math inline">\(\pm\)</span> 0.16 SE) heavier than the average female (sex 1). However, when we look at the variance components in the model including <code>sex</code> as a fixed effect, we see that they have changed slightly from the previous model:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="asreml-r-1.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error  z.ratio bound %ch
## vm(animal, ainv)  3.060441 0.5243571 5.836558     P   0
## units!units       2.938412 0.4161473 7.060991     P   0
## units!R           1.000000        NA       NA     F   0</code></pre>
<p>In fact since <code>sex</code> effects were previously contributing to the residual variance of the model, our estimate of <span class="math inline">\(V_R\)</span> (denoted <code>units!R</code> in the output) is now slightly lower than before. This has an important consequence for estimating heritability since if we calculate <span class="math inline">\(V_P\)</span> as <span class="math inline">\(V_A\)</span>+<span class="math inline">\(V_R\)</span> then as we include fixed effects we will soak up more residual variance driving <span class="math inline">\(V_P\)</span>. Assuming that <span class="math inline">\(V_A\)</span> is more or less unaffected by the fixed effects fitted then as <span class="math inline">\(V_P\)</span> goes down we expect our estimate of <span class="math inline">\(h^2\)</span> will go up:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="asreml-r-1.html#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model2, h2.bwt <span class="sc">~</span> V1 <span class="sc">/</span> (V1 <span class="sc">+</span> V2))</span></code></pre></div>
<pre><code>##        Estimate         SE
## h2.bwt 0.510171 0.07432388</code></pre>
<pre><code>##         Estimate         SE
## h2.bwt 0.4700163 0.07650881</code></pre>
<pre><code>##        Estimate         SE
## h2.bwt 0.510171 0.07432388</code></pre>
<p>Here <span class="math inline">\(h^2\)</span> has increased slightly from 0.47 to 0.51. Which is the better estimate? It depends on what your question is. The first is an estimate of the proportion of variance in birth weight explained by additive effects, the latter is an estimate of the proportion of variance in birth weight <em>after conditioning on sex</em> that is explained by additive effects.</p>
<p>An important piece of advice, each researcher should be consistent in how they name their estimates and always correcly describe which estimates they are using conditional or not (to avoid any confusion).</p>
</div>
<div id="adding-random-effects" class="section level3" number="2.2.4">
<h3><span class="header-section-number">2.2.4</span> Adding random effects</h3>
<p>This is done by simply modifying the model statement in the same way. For instance fitting</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="asreml-r-1.html#cb26-1" aria-hidden="true" tabindex="-1"></a>model3 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb26-2"><a href="asreml-r-1.html#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sex,</span>
<span id="cb26-3"><a href="asreml-r-1.html#cb26-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv) <span class="sc">+</span> byear,</span>
<span id="cb26-4"><a href="asreml-r-1.html#cb26-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb26-5"><a href="asreml-r-1.html#cb26-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb26-6"><a href="asreml-r-1.html#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb26-7"><a href="asreml-r-1.html#cb26-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:02 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2742.658           1.0    852 21:27:02    0.0
##  2     -2237.268           1.0    852 21:27:02    0.0
##  3     -1690.453           1.0    852 21:27:02    0.0
##  4     -1328.910           1.0    852 21:27:02    0.0
##  5     -1154.597           1.0    852 21:27:02    0.0
##  6     -1116.992           1.0    852 21:27:02    0.0
##  7     -1113.809           1.0    852 21:27:02    0.0
##  8     -1113.772           1.0    852 21:27:02    0.0
##  9     -1113.772           1.0    852 21:27:02    0.0</code></pre>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="asreml-r-1.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model3)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error  z.ratio bound %ch
## byear            0.8862604 0.2695918 3.287416     P   0
## vm(animal, ainv) 2.7068665 0.4422140 6.121169     P   0
## units!units      2.3092415 0.3451025 6.691466     P   0
## units!R          1.0000000        NA       NA     F   0</code></pre>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="asreml-r-1.html#cb30-1" aria-hidden="true" tabindex="-1"></a>(h2<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">vpredict</span>(model3, h2.bwt <span class="sc">~</span> V1 <span class="sc">/</span> (V1 <span class="sc">+</span> V2 <span class="sc">+</span> V3)))</span></code></pre></div>
<pre><code>##         Estimate         SE
## h2.bwt 0.1501533 0.03960814</code></pre>
<p>Here the variance in <code>bwt</code> explained by <code>byear</code> is 0.886 and, based on the <code>z.ratio</code>, appears to be significant (&gt;2). Thus we would conclude that year-to-year variation (<em>e.g.</em>, in weather, resource abundance) contributes to <span class="math inline">\(V_P\)</span>. Note that although <span class="math inline">\(V_A\)</span> has changed somewhat, as most of what is now partitioned as a birth year effect was previously partitioned as <span class="math inline">\(V_R\)</span>. Thus what we have really done here is to partition environmental effects into those arising from year-to-year differences versus everything else, and we do not really expect much change in <span class="math inline">\(h^2\)</span> (since now <span class="math inline">\(h^2 = V_A/ (V_A+V_{BY}+V_R)\)</span>).</p>
<p>However, we get a somewhat different result if we also add a random effect of <code>mother</code> to test for maternal effects:</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="asreml-r-1.html#cb32-1" aria-hidden="true" tabindex="-1"></a>model4 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb32-2"><a href="asreml-r-1.html#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sex,</span>
<span id="cb32-3"><a href="asreml-r-1.html#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv) <span class="sc">+</span> byear <span class="sc">+</span> mother,</span>
<span id="cb32-4"><a href="asreml-r-1.html#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb32-5"><a href="asreml-r-1.html#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb32-6"><a href="asreml-r-1.html#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb32-7"><a href="asreml-r-1.html#cb32-7" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:02 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2033.178           1.0    852 21:27:02    0.0
##  2     -1723.734           1.0    852 21:27:02    0.0
##  3     -1396.354           1.0    852 21:27:02    0.0
##  4     -1193.012           1.0    852 21:27:02    0.0
##  5     -1107.946           1.0    852 21:27:02    0.0
##  6     -1095.327           1.0    852 21:27:02    0.0
##  7     -1094.816           1.0    852 21:27:02    0.0
##  8     -1094.815           1.0    852 21:27:02    0.0</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="asreml-r-1.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model4)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error  z.ratio bound %ch
## byear            0.8820313 0.2632455 3.350604     P   0
## mother           1.1184698 0.2386239 4.687167     P   0
## vm(animal, ainv) 2.2985320 0.4962496 4.631806     P   0
## units!units      1.6290034 0.3714154 4.385934     P   0
## units!R          1.0000000        NA       NA     F   0</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="asreml-r-1.html#cb36-1" aria-hidden="true" tabindex="-1"></a>(h2<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="fu">vpredict</span>(model4, h2.bwt <span class="sc">~</span> V1 <span class="sc">/</span> (V1 <span class="sc">+</span> V2<span class="sc">+</span> V3 <span class="sc">+</span>V4)))</span></code></pre></div>
<pre><code>##         Estimate         SE
## h2.bwt 0.1487898 0.03861552</code></pre>
<p>Here partitioning of significant maternal variance has resulted in a further decrease in <span class="math inline">\(V_R\)</span> but also a decrease in <span class="math inline">\(V_A\)</span>. The latter is because maternal effects of the sort we simulated (fixed differences between mothers) will have the consequence of increasing similarity among maternal siblings. Consequently they can look very much like additive genetic effects and if present, but unmodelled, represent a type of “common environment effect”" that can - and will - cause upward bias in <span class="math inline">\(V_A\)</span> and so <span class="math inline">\(h^2\)</span>.
The “common environment” can be conceived as the indissociable sum of the maternal additive genetic effect (such as milk production) and the maternal environment or permanent environement (such as litter or nest environment). !!!!!!! need change !!!!</p>
</div>
<div id="testing-significance-of-random-effects" class="section level3" number="2.2.5">
<h3><span class="header-section-number">2.2.5</span> Testing significance of random effects</h3>
<p>A final point to note in this tutorial is that while the <code>z.ratio</code> (<code>component</code>/<code>std.error</code>) reported is a good indicator of likely statistical significance (&gt;1.96?), the standard errors are approximate and are not recommended for formal hypothesis testing. A better approach is to use likelihood-ratio tests.</p>
<p>For example, to test the significance of maternal effects we could compare models with and without the inclusion of maternal identity as a random effect and compare the final log-likelihoods of these models.</p>
<!--
??? do you think we should explain what is a likelihood here??
-->
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="asreml-r-1.html#cb38-1" aria-hidden="true" tabindex="-1"></a>model4<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -1094.815</code></pre>
<p>shows that the model including maternal identity has a log-likelihood of -1094.815, and</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="asreml-r-1.html#cb40-1" aria-hidden="true" tabindex="-1"></a>model3<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -1113.772</code></pre>
<p>shows that the model excluding maternal identity has a log-likelihood of -1113.772.</p>
<p>A test statistic equal to twice the absolute difference in these log-likelihoods is assumed to be distributed as Chi square with one degree of freedom. In this case we would conclude that the maternal effects are highly significant since:
2 <span class="math inline">\(\times\)</span> (-1094.8145793 - -1113.7719147) equals 37.9146708, and the p-value that comes with this is:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="asreml-r-1.html#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (model4<span class="sc">$</span>loglik <span class="sc">-</span> model3<span class="sc">$</span>loglik), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 7.390738e-10</code></pre>
<p>As P &lt; 0.0001 we would therefore conclude that the additional of maternal identity as a random effect significantly improves the model, given an increase in log-likelihood of approximately 19.</p>
</div>
<div id="futher-partitionning-the-variance" class="section level3" number="2.2.6">
<h3><span class="header-section-number">2.2.6</span> Futher partitionning the variance</h3>
<p>A population can be futher fragmented into different groups (such as females and males or treated and untreated). Some scientific questions require futher and deeper analysis of the dataset. To avoid multiple model (one for each group), we can directly partition the variance between groups in a unique model. In addition, by doing so, we can also test if the variance are different between groups.</p>
<p>As an example, we decide to take the model4 and partionnning the variance and residual only for the additive genetic variance. But further analysis will require to also partition the other components of variance.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="asreml-r-1.html#cb44-1" aria-hidden="true" tabindex="-1"></a>gryphon <span class="ot">&lt;-</span> gryphon[<span class="fu">order</span>(gryphon<span class="sc">$</span>sex),]</span>
<span id="cb44-2"><a href="asreml-r-1.html#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="asreml-r-1.html#cb44-3" aria-hidden="true" tabindex="-1"></a>model_SEX <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb44-4"><a href="asreml-r-1.html#cb44-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sex,</span>
<span id="cb44-5"><a href="asreml-r-1.html#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">at</span>(sex)<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span> byear <span class="sc">+</span> mother,</span>
<span id="cb44-6"><a href="asreml-r-1.html#cb44-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span><span class="fu">dsum</span>(<span class="sc">~</span>units <span class="sc">|</span> sex),</span>
<span id="cb44-7"><a href="asreml-r-1.html#cb44-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb44-8"><a href="asreml-r-1.html#cb44-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb44-9"><a href="asreml-r-1.html#cb44-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Multi-section model using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:02 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -1142.164           1.0    852 21:27:02    0.0
##  2     -1126.308           1.0    852 21:27:02    0.0
##  3     -1111.536           1.0    852 21:27:02    0.0
##  4     -1105.383           1.0    852 21:27:02    0.0
##  5     -1104.375           1.0    852 21:27:02    0.0
##  6     -1104.364           1.0    852 21:27:02    0.0</code></pre>
<p>First, the dataset need to be order by group (sex here). The variance need to be partitionned between group at both the random and residual levels. At the random effect, the fonction <code>at()</code> is perfect for this example. For the residual level, it is required to used the fonction <code>dsum()</code></p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="asreml-r-1.html#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_SEX)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                             component std.error  z.ratio bound %ch
## byear                       0.9001595 0.2690012 3.346303     P 0.0
## mother                      1.3396184 0.2663118 5.030263     P 0.0
## at(sex, 1):vm(animal, ainv) 1.4372390 0.6514306 2.206281     P 0.1
## at(sex, 2):vm(animal, ainv) 1.9861434 0.9974302 1.991261     P 0.3
## sex_1!R                     2.1706213 0.5542492 3.916327     P 0.0
## sex_2!R                     1.7112948 0.8246188 2.075256     P 0.3</code></pre>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="asreml-r-1.html#cb48-1" aria-hidden="true" tabindex="-1"></a>(h2.F <span class="ot">&lt;-</span> <span class="fu">vpredict</span>(model_SEX, h2.bwt <span class="sc">~</span> V3 <span class="sc">/</span> (V1 <span class="sc">+</span> V2 <span class="sc">+</span> V3 <span class="sc">+</span> V5)))</span></code></pre></div>
<pre><code>##         Estimate        SE
## h2.bwt 0.2457811 0.1070794</code></pre>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="asreml-r-1.html#cb50-1" aria-hidden="true" tabindex="-1"></a>(h2.M <span class="ot">&lt;-</span> <span class="fu">vpredict</span>(model_SEX, h2.bwt <span class="sc">~</span> V4 <span class="sc">/</span> (V1 <span class="sc">+</span> V2 <span class="sc">+</span> V4 <span class="sc">+</span> V6)))</span></code></pre></div>
<pre><code>##         Estimate        SE
## h2.bwt 0.3345244 0.1619218</code></pre>
<p>By partitionning the variance and the residual, the model estimates the <span class="math inline">\(V_A\)</span> and <span class="math inline">\(V_R\)</span> for each group (sex). Doing so, we can calculate the <span class="math inline">\(h^2\)</span> for each group (sex).
To test if the variance are different between groups, we can compare the model partitionned by sex <code>model_SEX</code> and the previous model without the partitionning <code>model4</code> with a likelihood ratio test (LRT) with 2 degrees of freedom since models have two components of variance of difference.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="asreml-r-1.html#cb52-1" aria-hidden="true" tabindex="-1"></a>model_SEX<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -1104.364</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="asreml-r-1.html#cb54-1" aria-hidden="true" tabindex="-1"></a>model4<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -1094.815</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="asreml-r-1.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (model_SEX<span class="sc">$</span>loglik <span class="sc">-</span> model4<span class="sc">$</span>loglik), <span class="dv">2</span>)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Here, we can see the <span class="math inline">\(h^2\)</span> seems to differ between sexes (0.25 and 0.33), the LRT partitionning the variance and the residual between group (sex) did not improved the fit of the model and so their variance are not significantly different.</p>
</div>
<div id="covariance-between-different-random-effect-and-possible-negative-variance" class="section level3" number="2.2.7">
<h3><span class="header-section-number">2.2.7</span> Covariance between different random effect and possible negative variance</h3>
<p>Variance represents the deviation of the distribution and it expected to be a positive values. However, it is happen in an animal the variance can be estiamted to be negative.
A negative variance could mean the mean within the random effect is less similar than expected by chance. Usually asreml-R will not allow the estimation of a negative variance and the model will create a boundary <code>B</code> close to 0 for this estimate.
But it is possible that a variance can be negative with a biological reason such as a sibling competition within the nest creating a negative among-individual covariance within the nest. We can exploit alternative model parameter to first allow the model to avoid the boundary and estimate a negative variance and second estimate a covaraince between two random effect (additive genetic varaince and nest (here mother) variance).
Just as a remember Mother as random effect is an only associated to the maternal effect, it is also include the nest effect which can be visual as maternal environement (permanent environement Vpe), the genetic maternal effet (Vma)</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="asreml-r-1.html#cb58-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb58-2"><a href="asreml-r-1.html#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb58-3"><a href="asreml-r-1.html#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv) <span class="sc">+</span> byear <span class="sc">+</span> mother,</span>
<span id="cb58-4"><a href="asreml-r-1.html#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb58-5"><a href="asreml-r-1.html#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb58-6"><a href="asreml-r-1.html#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>),</span>
<span id="cb58-7"><a href="asreml-r-1.html#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">start.values=</span> T )</span>
<span id="cb58-8"><a href="asreml-r-1.html#cb58-8" aria-hidden="true" tabindex="-1"></a>G.temp <span class="ot">&lt;-</span> temp<span class="sc">$</span>vparameters[(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),]</span>
<span id="cb58-9"><a href="asreml-r-1.html#cb58-9" aria-hidden="true" tabindex="-1"></a>G.temp<span class="sc">$</span>Constraint <span class="ot">&lt;-</span> <span class="st">&quot;U&quot;</span></span>
<span id="cb58-10"><a href="asreml-r-1.html#cb58-10" aria-hidden="true" tabindex="-1"></a>R.temp <span class="ot">&lt;-</span> temp<span class="sc">$</span>vparameters[<span class="sc">-</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>),]</span></code></pre></div>
<p>The argument <code>start.values=T</code> allowed the <code>temp</code> model to change its random parameters. We can create the two different matrices of the model and specify which parameters will be modified. For this example we modified the G matrix to fit all variance to be <code>U</code> unstructed (allowing negative variance in case its appeared).
The object G.temp and R.temp can be implemented in the follwing model as new parameters.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="asreml-r-1.html#cb59-1" aria-hidden="true" tabindex="-1"></a>model_5 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb59-2"><a href="asreml-r-1.html#cb59-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> bwt <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> sex,</span>
<span id="cb59-3"><a href="asreml-r-1.html#cb59-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">vm</span>(animal, ainv) <span class="sc">+</span> byear <span class="sc">+</span> mother,</span>
<span id="cb59-4"><a href="asreml-r-1.html#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">idv</span>(units),</span>
<span id="cb59-5"><a href="asreml-r-1.html#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb59-6"><a href="asreml-r-1.html#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="at">y =</span> <span class="st">&quot;omit&quot;</span>),</span>
<span id="cb59-7"><a href="asreml-r-1.html#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">R.param=</span>R.temp,<span class="at">G.param=</span>G.temp)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Thu Mar 18 21:27:03 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2033.178           1.0    852 21:27:03    0.0
##  2     -1723.734           1.0    852 21:27:03    0.0
##  3     -1396.354           1.0    852 21:27:03    0.0
##  4     -1193.012           1.0    852 21:27:03    0.0
##  5     -1107.946           1.0    852 21:27:03    0.0
##  6     -1095.327           1.0    852 21:27:03    0.0
##  7     -1094.816           1.0    852 21:27:03    0.0
##  8     -1094.815           1.0    852 21:27:03    0.0</code></pre>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="asreml-r-1.html#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_5)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error  z.ratio bound %ch
## byear            0.8820313 0.2632455 3.350604     U   0
## mother           1.1184698 0.2386239 4.687167     U   0
## vm(animal, ainv) 2.2985320 0.4962496 4.631806     U   0
## units!units      1.6290034 0.3714154 4.385934     P   0
## units!R          1.0000000        NA       NA     F   0</code></pre>
<!--
A more complex model can estimate the covariance between two random effect using the fonction `str`. For example, we can estimate the covariance between the additive genetic variance `Va` and the common environement `Vmother`.

need to add something about the fact that asreml does not work well with pedigree with integer as factor



```r
temp2 <- asreml(
  fixed = bwt ~ 1,
  random = ~ str( ~ vm(animal, ainv) + mother, ~ us(2):id(1149)) + byear,
  residual = ~ idv(units),
  data = gryphon,
  na.action = na.method(x = "omit", y = "omit"),
 # equate.levels = c("animal", "mother"),
  start.values=T)
G.temp2<-temp$vparameters[(1:4),]
G.temp2$Constraint <- "U"
R.temp2<-temp$vparameters[-(1:4),]

model_6 <- asreml(
  fixed = bwt ~ 1 + sex,
  random=~str(~vm(animal,ainv)+mother,~us(2):id(852)) + byear,
  residual = ~ idv(units),
  data = gryphon,
  na.action = na.method(x = "omit", y = "omit"),
  #equate.levels = c("animal", "mother"),
  R.param=R.temp2,G.param=G.temp2)
summary(model_6)$varcomp
```
the str fonction has two component, first the equation term `~vm(animal,Ainv)+mother` and second the structural term `~us(2):id(4500)`. Here within the structural term, we fit a 2x2 unstructured matrix `us(2)` which estimated the variance and the covariance between the random effect in the equation term. To sucessfully work, the structural term also requires the number of level identifyed witin `id()`.

!!!!!!!!!!! i am still blocked but this number 
length(unique(c(as.character(gryphon$animal), as.character(gryphon$mother))))#1084
length(unique(c(gryphon$mother)))#429
length(unique(c(gryphon$animal)))#1084
-->

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scenario-and-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="gremlin-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/wam_tuto/02_01-univ_asreml.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["wam_tuto.pdf", "wam_tuto.epub", "wam_tuto.mobi"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toc_depth": 4
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
