<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>4.2 Asreml-R | How to fit an animal model</title>
  <meta name="description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="generator" content="bookdown 0.26 and GitBook 2.6.7" />

  <meta property="og:title" content="4.2 Asreml-R | How to fit an animal model" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="github-repo" content="JulienGAMartin/wam_tuto" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4.2 Asreml-R | How to fit an animal model" />
  
  <meta name="twitter:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />
<meta name="author" content="Matthieu Videlier" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scenario-and-data-2.html"/>
<link rel="next" href="gremlin-3.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">How to fit an animal model</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1.1</b> Data</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data.html"><a href="data.html#data-files"><i class="fa fa-check"></i><b>1.1.1</b> Data files</a></li>
<li class="chapter" data-level="1.1.2" data-path="data.html"><a href="data.html#notes-on-data-and-pedigree"><i class="fa fa-check"></i><b>1.1.2</b> Notes on data and pedigree</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>1.2</b> R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="r.html"><a href="r.html#r-packages"><i class="fa fa-check"></i><b>1.2.1</b> R packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-animal-model.html"><a href="univariate-animal-model.html"><i class="fa fa-check"></i><b>2</b> Univariate animal model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html"><i class="fa fa-check"></i><b>2.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html#scenario"><i class="fa fa-check"></i><b>2.1.1</b> Scenario</a></li>
<li class="chapter" data-level="2.1.2" data-path="scenario-and-data.html"><a href="scenario-and-data.html#data-files-1"><i class="fa fa-check"></i><b>2.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html"><i class="fa fa-check"></i><b>2.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="asreml-r-1.html"><a href="asreml-r-1.html#running-the-model"><i class="fa fa-check"></i><b>2.2.1</b> Running the model</a></li>
<li class="chapter" data-level="2.2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html#estimating-heritability"><i class="fa fa-check"></i><b>2.2.2</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.2.3" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-fixed-effects"><i class="fa fa-check"></i><b>2.2.3</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.2.4" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-random-effects"><i class="fa fa-check"></i><b>2.2.4</b> Adding random effects</a></li>
<li class="chapter" data-level="2.2.5" data-path="asreml-r-1.html"><a href="asreml-r-1.html#testing-significance-of-random-effects"><i class="fa fa-check"></i><b>2.2.5</b> Testing significance of random effects</a></li>
<li class="chapter" data-level="2.2.6" data-path="asreml-r-1.html"><a href="asreml-r-1.html#further-partitioning-the-variance"><i class="fa fa-check"></i><b>2.2.6</b> Further partitioning the variance</a></li>
<li class="chapter" data-level="2.2.7" data-path="asreml-r-1.html"><a href="asreml-r-1.html#modification-of-the-varaince-matrix-parameters"><i class="fa fa-check"></i><b>2.2.7</b> Modification of the varaince matrix parameters</a></li>
<li class="chapter" data-level="2.2.8" data-path="asreml-r-1.html"><a href="asreml-r-1.html#covariance-between-two-random-effects"><i class="fa fa-check"></i><b>2.2.8</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="gremlin-1.html"><a href="gremlin-1.html"><i class="fa fa-check"></i><b>2.3</b> gremlin</a></li>
<li class="chapter" data-level="2.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html"><i class="fa fa-check"></i><b>2.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#running-the-model-1"><i class="fa fa-check"></i><b>2.4.1</b> Running the model</a></li>
<li class="chapter" data-level="2.4.2" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#change-in-iteration-and-sampling"><i class="fa fa-check"></i><b>2.4.2</b> Change in iteration and sampling</a></li>
<li class="chapter" data-level="2.4.3" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#change-priors-parameters"><i class="fa fa-check"></i><b>2.4.3</b> Change priors parameters</a></li>
<li class="chapter" data-level="2.4.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#estimating-heritability-1"><i class="fa fa-check"></i><b>2.4.4</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.4.5" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-fixed-effects-1"><i class="fa fa-check"></i><b>2.4.5</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.4.6" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-random-effects-1"><i class="fa fa-check"></i><b>2.4.6</b> Adding random effects</a></li>
<li class="chapter" data-level="2.4.7" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#testing-significance-of-variance-components"><i class="fa fa-check"></i><b>2.4.7</b> Testing significance of variance components</a></li>
<li class="chapter" data-level="2.4.8" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#further-partitioning-variance"><i class="fa fa-check"></i><b>2.4.8</b> Further partitioning variance</a></li>
<li class="chapter" data-level="2.4.9" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#modification-of-model-parameter"><i class="fa fa-check"></i><b>2.4.9</b> Modification of model parameter</a></li>
<li class="chapter" data-level="2.4.10" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#covariance-between-two-random-effects-1"><i class="fa fa-check"></i><b>2.4.10</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="brms-1.html"><a href="brms-1.html"><i class="fa fa-check"></i><b>2.5</b> brms</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="brms-1.html"><a href="brms-1.html#running-the-model-2"><i class="fa fa-check"></i><b>2.5.1</b> Running the model</a></li>
<li class="chapter" data-level="2.5.2" data-path="brms-1.html"><a href="brms-1.html#adding-fixed-effects-2"><i class="fa fa-check"></i><b>2.5.2</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.5.3" data-path="brms-1.html"><a href="brms-1.html#adding-random-effects-2"><i class="fa fa-check"></i><b>2.5.3</b> Adding random effects</a></li>
<li class="chapter" data-level="2.5.4" data-path="brms-1.html"><a href="brms-1.html#testing-significance-of-variance-components-1"><i class="fa fa-check"></i><b>2.5.4</b> Testing significance of variance components</a></li>
<li class="chapter" data-level="2.5.5" data-path="brms-1.html"><a href="brms-1.html#further-partitioning-of-the-variance"><i class="fa fa-check"></i><b>2.5.5</b> Further partitioning of the variance</a></li>
<li class="chapter" data-level="2.5.6" data-path="brms-1.html"><a href="brms-1.html#modification-of-model-parameter-1"><i class="fa fa-check"></i><b>2.5.6</b> Modification of model parameter</a></li>
<li class="chapter" data-level="2.5.7" data-path="brms-1.html"><a href="brms-1.html#covariance-between-two-random-effects-2"><i class="fa fa-check"></i><b>2.5.7</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="stan.html"><a href="stan.html"><i class="fa fa-check"></i><b>2.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multivariate-animal-model.html"><a href="multivariate-animal-model.html"><i class="fa fa-check"></i><b>3</b> Multivariate animal model</a>
<ul>
<li class="chapter" data-level="3.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html"><i class="fa fa-check"></i><b>3.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#scenario-1"><i class="fa fa-check"></i><b>3.1.1</b> Scenario</a></li>
<li class="chapter" data-level="3.1.2" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#gryphon-files"><i class="fa fa-check"></i><b>3.1.2</b> gryphon files</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="asreml-biv.html"><a href="asreml-biv.html"><i class="fa fa-check"></i><b>3.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="asreml-biv.html"><a href="asreml-biv.html#running-the-model-3"><i class="fa fa-check"></i><b>3.2.1</b> Running the model</a></li>
<li class="chapter" data-level="3.2.2" data-path="asreml-biv.html"><a href="asreml-biv.html#adding-fixed-and-random-effects"><i class="fa fa-check"></i><b>3.2.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.2.3" data-path="asreml-biv.html"><a href="asreml-biv.html#significance-testing"><i class="fa fa-check"></i><b>3.2.3</b> Significance testing</a></li>
<li class="chapter" data-level="3.2.4" data-path="asreml-biv.html"><a href="asreml-biv.html#estimate-directly-the-genetic-correlation-within-the-model"><i class="fa fa-check"></i><b>3.2.4</b> Estimate directly the genetic correlation within the model</a></li>
<li class="chapter" data-level="3.2.5" data-path="asreml-biv.html"><a href="asreml-biv.html#visualisation-of-the-correlation-aka-blup-extraction"><i class="fa fa-check"></i><b>3.2.5</b> Visualisation of the correlation (aka BLUP extraction)</a></li>
<li class="chapter" data-level="3.2.6" data-path="asreml-biv.html"><a href="asreml-biv.html#partitionning-covariance-between-groups"><i class="fa fa-check"></i><b>3.2.6</b> Partitionning (co)variance between groups</a></li>
<li class="chapter" data-level="3.2.7" data-path="asreml-biv.html"><a href="asreml-biv.html#between-groups-covariances-and-the-b-matrix"><i class="fa fa-check"></i><b>3.2.7</b> Between groups (co)variances and the B-matrix</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="gremlin-2.html"><a href="gremlin-2.html"><i class="fa fa-check"></i><b>3.3</b> gremlin</a></li>
<li class="chapter" data-level="3.4" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html"><i class="fa fa-check"></i><b>3.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#fitting-the-model"><i class="fa fa-check"></i><b>3.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.4.2" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#adding-fixed-and-random-effects-1"><i class="fa fa-check"></i><b>3.4.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.4.3" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#direct-estimate-of-the-correlation-instead-of-the-covariance."><i class="fa fa-check"></i><b>3.4.3</b> Direct estimate of the correlation instead of the covariance.</a></li>
<li class="chapter" data-level="3.4.4" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#partitioning-covariances"><i class="fa fa-check"></i><b>3.4.4</b> Partitioning (co)variances</a></li>
<li class="chapter" data-level="3.4.5" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#between-groups-covariances-and-the-b-matrix-1"><i class="fa fa-check"></i><b>3.4.5</b> Between groups (co)variances and the B-matrix</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="brms-2.html"><a href="brms-2.html"><i class="fa fa-check"></i><b>3.5</b> brms</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="brms-2.html"><a href="brms-2.html#fitting-the-model-1"><i class="fa fa-check"></i><b>3.5.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.5.2" data-path="brms-2.html"><a href="brms-2.html#adding-fixed-and-random-effects-2"><i class="fa fa-check"></i><b>3.5.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.5.3" data-path="brms-2.html"><a href="brms-2.html#partitioning-covariances-1"><i class="fa fa-check"></i><b>3.5.3</b> Partitioning (co)variances</a></li>
<li class="chapter" data-level="3.5.4" data-path="brms-2.html"><a href="brms-2.html#between-groups-covariances-and-the-b-matrix-2"><i class="fa fa-check"></i><b>3.5.4</b> Between groups (co)variances and the B-matrix</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="stan-1.html"><a href="stan-1.html"><i class="fa fa-check"></i><b>3.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rep_measures.html"><a href="rep_measures.html"><i class="fa fa-check"></i><b>4</b> A repeated measures animal model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html"><i class="fa fa-check"></i><b>4.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#scenario-2"><i class="fa fa-check"></i><b>4.1.1</b> scenario</a></li>
<li class="chapter" data-level="4.1.2" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#data-files-2"><i class="fa fa-check"></i><b>4.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html"><i class="fa fa-check"></i><b>4.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="asreml-r-2.html"><a href="asreml-r-2.html#estimating-repeatability"><i class="fa fa-check"></i><b>4.2.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.2.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html#partitioning-additive-and-permanent-environment-effects"><i class="fa fa-check"></i><b>4.2.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.2.3" data-path="asreml-r-2.html"><a href="asreml-r-2.html#adding-additional-effects-and-testing-significance"><i class="fa fa-check"></i><b>4.2.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="gremlin-3.html"><a href="gremlin-3.html"><i class="fa fa-check"></i><b>4.3</b> gremlin</a></li>
<li class="chapter" data-level="4.4" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html"><i class="fa fa-check"></i><b>4.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#estimating-repeatability-1"><i class="fa fa-check"></i><b>4.4.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.4.2" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#partitioning-additive-and-permanent-environment-effects-1"><i class="fa fa-check"></i><b>4.4.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.4.3" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#adding-additional-effects-and-testing-significance-1"><i class="fa fa-check"></i><b>4.4.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="brms-3.html"><a href="brms-3.html"><i class="fa fa-check"></i><b>4.5</b> brms</a></li>
<li class="chapter" data-level="4.6" data-path="stan-2.html"><a href="stan-2.html"><i class="fa fa-check"></i><b>4.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quick-comparison-of-codes.html"><a href="quick-comparison-of-codes.html"><i class="fa fa-check"></i><b>5</b> Quick comparison of codes</a>
<ul>
<li class="chapter" data-level="5.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html"><i class="fa fa-check"></i><b>5.1</b> Univariate model with repeated measures</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#asreml-r-3"><i class="fa fa-check"></i><b>5.1.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.1.2" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#gremlin-4"><i class="fa fa-check"></i><b>5.1.2</b> gremlin</a></li>
<li class="chapter" data-level="5.1.3" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#mcmcglmm-4"><i class="fa fa-check"></i><b>5.1.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.1.4" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#brms-4"><i class="fa fa-check"></i><b>5.1.4</b> brms</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bivariate-model.html"><a href="bivariate-model.html"><i class="fa fa-check"></i><b>5.2</b> bivariate model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bivariate-model.html"><a href="bivariate-model.html#asreml-r-4"><i class="fa fa-check"></i><b>5.2.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.2.2" data-path="bivariate-model.html"><a href="bivariate-model.html#gremlin-5"><i class="fa fa-check"></i><b>5.2.2</b> gremlin</a></li>
<li class="chapter" data-level="5.2.3" data-path="bivariate-model.html"><a href="bivariate-model.html#mcmcglmm-5"><i class="fa fa-check"></i><b>5.2.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.2.4" data-path="bivariate-model.html"><a href="bivariate-model.html#brms-5"><i class="fa fa-check"></i><b>5.2.4</b> brms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">How to fit an animal model</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="asreml-r-2" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Asreml-R<a href="asreml-r-2.html#asreml-r-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First we need to load the <code>asreml</code> library:</p>
<div class="sourceCode" id="cb582"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb582-1"><a href="asreml-r-2.html#cb582-1" aria-hidden="true"></a><span class="kw">library</span>(asreml)</span></code></pre></div>
<div id="estimating-repeatability" class="section level3 hasAnchor" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Estimating repeatability<a href="asreml-r-2.html#estimating-repeatability" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With repeated measures on individuals it is often of interest to see how repeatable a trait is.
We can estimate the repeatability of a trait as the proportion of phenotypic variance <span class="math inline">\(V_P\)</span> explained by individual variance <span class="math inline">\(V_{ind}\)</span>; <span class="math inline">\(R = V_{ind}/V_P = V_{ind}/(V_{ind}+V_R)\)</span>.</p>
<div class="sourceCode" id="cb583"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb583-1"><a href="asreml-r-2.html#cb583-1" aria-hidden="true"></a>modelv &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb583-2"><a href="asreml-r-2.html#cb583-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span><span class="dv">1</span>,</span>
<span id="cb583-3"><a href="asreml-r-2.html#cb583-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span>animal,</span>
<span id="cb583-4"><a href="asreml-r-2.html#cb583-4" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb583-5"><a href="asreml-r-2.html#cb583-5" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb583-6"><a href="asreml-r-2.html#cb583-6" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb583-7"><a href="asreml-r-2.html#cb583-7" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:26 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -10182.83           1.0   1606 15:19:26    0.0
##  2      -8266.10           1.0   1606 15:19:26    0.0
##  3      -6145.01           1.0   1606 15:19:26    0.0
##  4      -4651.57           1.0   1606 15:19:26    0.0
##  5      -3819.31           1.0   1606 15:19:26    0.0
##  6      -3554.22           1.0   1606 15:19:26    0.0
##  7      -3501.56           1.0   1606 15:19:26    0.0
##  8      -3497.58           1.0   1606 15:19:26    0.0
##  9      -3497.54           1.0   1606 15:19:26    0.0
## 10      -3497.54           1.0   1606 15:19:26    0.0</code></pre>
<div class="sourceCode" id="cb585"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb585-1"><a href="asreml-r-2.html#cb585-1" aria-hidden="true"></a><span class="kw">plot</span>(modelv)</span></code></pre></div>
<p><img src="wam_tuto_files/figure-html/unnamed-chunk-171-1.svg" width="672" />
The model assumption seems correct, so we can look at the different estimates.
Note that since we want to estimate the amount of variance explained by individual identity (rather than by additive genetic effects), we fit <code>animal</code> as a normal random effect and we don’t associate it with the pedigree.
Here, we also ask the model to remove any <code>NA</code> in <code>laydate</code>.</p>
<p>This model partitions the phenotypic variance in <code>laydate</code> as follows:</p>
<div class="sourceCode" id="cb586"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb586-1"><a href="asreml-r-2.html#cb586-1" aria-hidden="true"></a><span class="kw">summary</span>(modelv)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##             component std.error   z.ratio bound %ch
## animal       11.08634 1.1794319  9.399728     P   0
## units!units  21.29643 0.8896196 23.938798     P   0
## units!R       1.00000        NA        NA     F   0</code></pre>
<p>Between-individual (or among-individual) variance is given by the <code>animal</code> component, while the residual component (<code>units!units</code>) represents within-individual variance. Here then the repeatability of the trait can be determined by hand as 0.34 (<em>i.e.</em>, as 11.086/(11.086 + 21.296)).</p>
<p>Mean lay date might change with age, so we could ask what the repeatability of lay date is after conditioning on age. This would be done by adding <code>age</code> into the model as a fixed effect.</p>
<div class="sourceCode" id="cb588"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb588-1"><a href="asreml-r-2.html#cb588-1" aria-hidden="true"></a>modelw &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb588-2"><a href="asreml-r-2.html#cb588-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age,</span>
<span id="cb588-3"><a href="asreml-r-2.html#cb588-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span>animal,</span>
<span id="cb588-4"><a href="asreml-r-2.html#cb588-4" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb588-5"><a href="asreml-r-2.html#cb588-5" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb588-6"><a href="asreml-r-2.html#cb588-6" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb588-7"><a href="asreml-r-2.html#cb588-7" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:27 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -8402.968           1.0   1602 15:19:27    0.0
##  2     -6912.361           1.0   1602 15:19:27    0.0
##  3     -5274.379           1.0   1602 15:19:27    0.0
##  4     -4143.634           1.0   1602 15:19:27    0.0
##  5     -3541.895           1.0   1602 15:19:27    0.0
##  6     -3372.909           1.0   1602 15:19:27    0.0
##  7     -3347.670           1.0   1602 15:19:27    0.0
##  8     -3346.655           1.0   1602 15:19:27    0.0
##  9     -3346.652           1.0   1602 15:19:27    0.0</code></pre>
<div class="sourceCode" id="cb590"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb590-1"><a href="asreml-r-2.html#cb590-1" aria-hidden="true"></a><span class="kw">summary</span>(modelw)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##             component std.error  z.ratio bound %ch
## animal       12.28982  1.156115 10.63027     P   0
## units!units  16.37989  0.686619 23.85586     P   0
## units!R       1.00000        NA       NA     F   0</code></pre>
<p>The repeatability of lay date, after accounting for age effects, is now estimated as 0.43 (<em>i.e.</em>, as 12.29/(12.29 + 16.38)).
So, just as we saw when estimating <span class="math inline">\(h^2\)</span> in Tutorial 1, the inclusion of fixed effects will alter the estimated effect size
<!-- effect size or just the variance estimate -->
if we determine total phenotypic variance as the sum of the variance components. Thus, proper interpretation is vital.</p>
<div class="sourceCode" id="cb592"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb592-1"><a href="asreml-r-2.html#cb592-1" aria-hidden="true"></a><span class="kw">summary</span>(modelw, <span class="dt">coef =</span> <span class="ot">TRUE</span>)<span class="op">$</span>coef.fixed</span>
<span id="cb592-2"><a href="asreml-r-2.html#cb592-2" aria-hidden="true"></a><span class="kw">wald.asreml</span>(modelw, <span class="dt">ssType =</span> <span class="st">&quot;conditional&quot;</span>, <span class="dt">denDF =</span> <span class="st">&quot;numeric&quot;</span>)</span></code></pre></div>
<pre><code>##              solution std error   z.ratio
## age_2        0.000000        NA        NA
## age_3        2.577777 0.3355253  7.682811
## age_4        4.247276 0.3309028 12.835418
## age_5        6.094490 0.3375537 18.054872
## age_6        3.132675 0.3371074  9.292811
## (Intercept) 20.305073 0.2899515 70.029214</code></pre>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:27 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -3346.652           1.0   1602 15:19:27    0.0
##  2     -3346.652           1.0   1602 15:19:27    0.0
##  3     -3346.652           1.0   1602 15:19:27    0.0</code></pre>
<pre><code>## 
##             Df  denDF   F.inc   F.con Margin          Pr
## (Intercept)  1  460.2 14880.0 14880.0        0.00000e+00
## age          4 1225.3    88.7    88.7      A 2.89474e-66</code></pre>
<p>Here age is modeled as a 5-level factor (specified using the function <code>as.factor()</code> at the beginning of the analysis). We could equally have fitted it as a continuous variable, in which case, given potential for a late life decline, we would probably also include a quadratic term.
In addition, using <code>age</code> as continuous variable can help in saving some degree of freedom in the analysis.</p>
<!-- C1 I dont know why the quadratic fixed effect dont work, need to remember how to do this -->
</div>
<div id="partitioning-additive-and-permanent-environment-effects" class="section level3 hasAnchor" number="4.2.2">
<h3><span class="header-section-number">4.2.2</span> Partitioning additive and permanent environment effects<a href="asreml-r-2.html#partitioning-additive-and-permanent-environment-effects" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Generally we expect that the repeatability will set the upper limit for heritability since among individual variation can be decomposed in the additive genetic variation and non additive genetic variation. In other word, the additive genetic variation is a subcomponent of the difference between individuals.
Non-additive contributions to fixed among-individual differences are normally referred to as <em>permanent environment effects</em>. If a trait has repeated measures then it is necessary to model permanent environment effects in an animal model to prevent upward bias in <span class="math inline">\(V_A\)</span>.</p>
<p>To illustrate it, we first fit the animal model:</p>
<div class="sourceCode" id="cb596"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb596-1"><a href="asreml-r-2.html#cb596-1" aria-hidden="true"></a>gryphonped &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;data/gryphonped.csv&quot;</span>)</span>
<span id="cb596-2"><a href="asreml-r-2.html#cb596-2" aria-hidden="true"></a>gryphonped<span class="op">$</span>id &lt;-<span class="st"> </span><span class="kw">as.factor</span>(gryphonped<span class="op">$</span>id)</span>
<span id="cb596-3"><a href="asreml-r-2.html#cb596-3" aria-hidden="true"></a>gryphonped<span class="op">$</span>father &lt;-<span class="st"> </span><span class="kw">as.factor</span>(gryphonped<span class="op">$</span>father)</span>
<span id="cb596-4"><a href="asreml-r-2.html#cb596-4" aria-hidden="true"></a>gryphonped<span class="op">$</span>mother &lt;-<span class="st"> </span><span class="kw">as.factor</span>(gryphonped<span class="op">$</span>mother)</span>
<span id="cb596-5"><a href="asreml-r-2.html#cb596-5" aria-hidden="true"></a></span>
<span id="cb596-6"><a href="asreml-r-2.html#cb596-6" aria-hidden="true"></a>ainv &lt;-<span class="st"> </span><span class="kw">ainverse</span>(gryphonped)</span>
<span id="cb596-7"><a href="asreml-r-2.html#cb596-7" aria-hidden="true"></a></span>
<span id="cb596-8"><a href="asreml-r-2.html#cb596-8" aria-hidden="true"></a>modelx &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb596-9"><a href="asreml-r-2.html#cb596-9" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age,</span>
<span id="cb596-10"><a href="asreml-r-2.html#cb596-10" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="kw">vm</span>(animal, ainv),</span>
<span id="cb596-11"><a href="asreml-r-2.html#cb596-11" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb596-12"><a href="asreml-r-2.html#cb596-12" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb596-13"><a href="asreml-r-2.html#cb596-13" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb596-14"><a href="asreml-r-2.html#cb596-14" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:27 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -8751.390           1.0   1602 15:19:27    0.0
##  2     -7169.205           1.0   1602 15:19:27    0.0
##  3     -5427.604           1.0   1602 15:19:27    0.0
##  4     -4219.598           1.0   1602 15:19:27    0.0
##  5     -3569.815           1.0   1602 15:19:27    0.0
##  6     -3382.341           1.0   1602 15:19:27    0.0
##  7     -3352.867           1.0   1602 15:19:27    0.0
##  8     -3351.565           1.0   1602 15:19:27    0.0
##  9     -3351.560           1.0   1602 15:19:27    0.0</code></pre>
<p>Variance components are almost unchanged if we compare the previous model:</p>
<div class="sourceCode" id="cb598"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb598-1"><a href="asreml-r-2.html#cb598-1" aria-hidden="true"></a><span class="kw">summary</span>(modelx)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error   z.ratio bound %ch
## vm(animal, ainv)  13.91784  1.443968  9.638607     P   0
## units!units       16.84008  0.707365 23.806768     P   0
## units!R            1.00000        NA        NA     F   0</code></pre>
<div class="sourceCode" id="cb600"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb600-1"><a href="asreml-r-2.html#cb600-1" aria-hidden="true"></a><span class="kw">summary</span>(modelw)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##             component std.error  z.ratio bound %ch
## animal       12.28982  1.156115 10.63027     P   0
## units!units  16.37989  0.686619 23.85586     P   0
## units!R       1.00000        NA       NA     F   0</code></pre>
<p>This suggests that most of the among-individual variance is – rightly or wrongly – being partitioned as <span class="math inline">\(V_A\)</span> here. To instead to obtain an unbiased estimate of <span class="math inline">\(V_A\)</span>, we need to partition for both additive genetic <em>and</em> non-genetic sources of individual variation. We do it by fitting <code>animal</code> twice, once with a pedigree, and once without a pedigree (using <code>ide()</code>).
Here, the command <code>ide</code> allow to create a second effect using a similar variable.</p>
<div class="sourceCode" id="cb602"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb602-1"><a href="asreml-r-2.html#cb602-1" aria-hidden="true"></a>modely &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb602-2"><a href="asreml-r-2.html#cb602-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age,</span>
<span id="cb602-3"><a href="asreml-r-2.html#cb602-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="kw">vm</span>(animal, ainv) <span class="op">+</span><span class="st"> </span><span class="kw">ide</span>(animal),</span>
<span id="cb602-4"><a href="asreml-r-2.html#cb602-4" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb602-5"><a href="asreml-r-2.html#cb602-5" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb602-6"><a href="asreml-r-2.html#cb602-6" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb602-7"><a href="asreml-r-2.html#cb602-7" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:27 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -7731.394           1.0   1602 15:19:27    0.0
##  2     -6426.548           1.0   1602 15:19:27    0.0
##  3     -4997.252           1.0   1602 15:19:27    0.0
##  4     -4018.486           1.0   1602 15:19:27    0.0
##  5     -3504.988           1.0   1602 15:19:27    0.0
##  6     -3363.160           1.0   1602 15:19:27    0.0
##  7     -3341.611           1.0   1602 15:19:27    0.0
##  8     -3340.682           1.0   1602 15:19:27    0.0
##  9     -3340.679           1.0   1602 15:19:27    0.0</code></pre>
<div class="sourceCode" id="cb604"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb604-1"><a href="asreml-r-2.html#cb604-1" aria-hidden="true"></a><span class="kw">summary</span>(modely)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error   z.ratio bound %ch
## vm(animal, ainv)  4.876101 1.8087709  2.695809     P   0
## ide(animal)       7.400983 1.7280113  4.282948     P   0
## units!units      16.380188 0.6866189 23.856300     P   0
## units!R           1.000000        NA        NA     F   0</code></pre>
<p>The estimate of <span class="math inline">\(V_A\)</span> is now much lower since the additive and permanent environment effects are being properly separated. We can estimate <span class="math inline">\(h^2\)</span> and the repeatability from this model:</p>
<div class="sourceCode" id="cb606"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb606-1"><a href="asreml-r-2.html#cb606-1" aria-hidden="true"></a><span class="kw">vpredict</span>(modely, h2 <span class="op">~</span><span class="st"> </span>V1 <span class="op">/</span><span class="st"> </span>(V1 <span class="op">+</span><span class="st"> </span>V2 <span class="op">+</span><span class="st"> </span>V3))</span></code></pre></div>
<pre><code>##     Estimate         SE
## h2 0.1701523 0.06073974</code></pre>
<div class="sourceCode" id="cb608"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb608-1"><a href="asreml-r-2.html#cb608-1" aria-hidden="true"></a><span class="kw">vpredict</span>(modely, repeatability <span class="op">~</span><span class="st"> </span>(V1 <span class="op">+</span><span class="st"> </span>V2) <span class="op">/</span><span class="st"> </span>(V1 <span class="op">+</span><span class="st"> </span>V2 <span class="op">+</span><span class="st"> </span>V3))</span></code></pre></div>
<pre><code>##                Estimate         SE
## repeatability 0.4284108 0.02741602</code></pre>
</div>
<div id="adding-additional-effects-and-testing-significance" class="section level3 hasAnchor" number="4.2.3">
<h3><span class="header-section-number">4.2.3</span> Adding additional effects and testing significance<a href="asreml-r-2.html#adding-additional-effects-and-testing-significance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Models of repeated measures can be extended to include other fixed or random effects. For example try including year of measurement (<code>year</code>) and birth year (<code>byear</code>) as random effects.</p>
<div class="sourceCode" id="cb610"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb610-1"><a href="asreml-r-2.html#cb610-1" aria-hidden="true"></a>modelz &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb610-2"><a href="asreml-r-2.html#cb610-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age,</span>
<span id="cb610-3"><a href="asreml-r-2.html#cb610-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="kw">vm</span>(animal, ainv) <span class="op">+</span><span class="st"> </span><span class="kw">ide</span>(animal) <span class="op">+</span></span>
<span id="cb610-4"><a href="asreml-r-2.html#cb610-4" aria-hidden="true"></a><span class="st">    </span>year <span class="op">+</span><span class="st"> </span>byear,</span>
<span id="cb610-5"><a href="asreml-r-2.html#cb610-5" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb610-6"><a href="asreml-r-2.html#cb610-6" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb610-7"><a href="asreml-r-2.html#cb610-7" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb610-8"><a href="asreml-r-2.html#cb610-8" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:28 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4650.748           1.0   1602 15:19:28    0.0
##  2     -4088.264           1.0   1602 15:19:28    0.0
##  3     -3494.147           1.0   1602 15:19:28    0.0
##  4     -3127.161           1.0   1602 15:19:28    0.0 (1 restrained)
##  5     -2976.449           1.0   1602 15:19:28    0.0 (1 restrained)
##  6     -2955.785           1.0   1602 15:19:28    0.0 (1 restrained)
##  7     -2955.097           1.0   1602 15:19:28    0.0 (1 restrained)
##  8     -2955.095           1.0   1602 15:19:28    0.0 (1 restrained)
##  9     -2955.095           1.0   1602 15:19:28    0.0</code></pre>
<div class="sourceCode" id="cb612"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb612-1"><a href="asreml-r-2.html#cb612-1" aria-hidden="true"></a><span class="kw">summary</span>(modelz)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##                     component std.error   z.ratio bound %ch
## byear            1.650876e-07        NA        NA     B   0
## year             7.938576e+00 1.9344619  4.103765     P   0
## vm(animal, ainv) 4.815136e+00 1.6682351  2.886365     P   0
## ide(animal)      8.433325e+00 1.5495778  5.442337     P   0
## units!units      7.795560e+00 0.3324411 23.449443     P   0
## units!R          1.000000e+00        NA        NA     F   0</code></pre>
<p>This model will return additional variance components corresponding to variation in lay dates between years of measurement and between birth cohorts of females. <span class="math inline">\(V_{byear}\)</span> is very low and <code>B</code> appeared which tell us that the model had fixed the variance as a boundary. If you compare this model to a reduced model with byear excluded the log-likelihood remains unchanged.</p>
<div class="sourceCode" id="cb614"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb614-1"><a href="asreml-r-2.html#cb614-1" aria-hidden="true"></a>modelz_<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb614-2"><a href="asreml-r-2.html#cb614-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age,</span>
<span id="cb614-3"><a href="asreml-r-2.html#cb614-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="kw">vm</span>(animal, ainv) <span class="op">+</span><span class="st"> </span><span class="kw">ide</span>(animal) <span class="op">+</span></span>
<span id="cb614-4"><a href="asreml-r-2.html#cb614-4" aria-hidden="true"></a><span class="st">    </span>year,</span>
<span id="cb614-5"><a href="asreml-r-2.html#cb614-5" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb614-6"><a href="asreml-r-2.html#cb614-6" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb614-7"><a href="asreml-r-2.html#cb614-7" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb614-8"><a href="asreml-r-2.html#cb614-8" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:28 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4665.606           1.0   1602 15:19:28    0.0
##  2     -4097.928           1.0   1602 15:19:28    0.0
##  3     -3498.611           1.0   1602 15:19:28    0.0
##  4     -3128.789           1.0   1602 15:19:28    0.0
##  5     -2976.883           1.0   1602 15:19:28    0.0
##  6     -2955.806           1.0   1602 15:19:28    0.0
##  7     -2955.096           1.0   1602 15:19:28    0.0
##  8     -2955.095           1.0   1602 15:19:28    0.0</code></pre>
<div class="sourceCode" id="cb616"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb616-1"><a href="asreml-r-2.html#cb616-1" aria-hidden="true"></a><span class="kw">summary</span>(modelz_<span class="dv">2</span>)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error   z.ratio bound %ch
## year              7.938576 1.9344829  4.103720     P   0
## vm(animal, ainv)  4.815137 1.6682366  2.886364     P   0
## ide(animal)       8.433324 1.5495828  5.442319     P   0
## units!units       7.795560 0.3324384 23.449637     P   0
## units!R           1.000000        NA        NA     F   0</code></pre>
<div class="sourceCode" id="cb618"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb618-1"><a href="asreml-r-2.html#cb618-1" aria-hidden="true"></a>modelz<span class="op">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2955.095</code></pre>
<div class="sourceCode" id="cb620"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb620-1"><a href="asreml-r-2.html#cb620-1" aria-hidden="true"></a>modelz_<span class="dv">2</span><span class="op">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2955.095</code></pre>
<div class="sourceCode" id="cb622"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb622-1"><a href="asreml-r-2.html#cb622-1" aria-hidden="true"></a><span class="dv">1</span> <span class="op">-</span><span class="st"> </span><span class="kw">pchisq</span>(<span class="dv">2</span> <span class="op">*</span><span class="st"> </span>(modelz_<span class="dv">2</span><span class="op">$</span>loglik <span class="op">-</span><span class="st"> </span>modelz<span class="op">$</span>loglik), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.9990425</code></pre>
<p><code>year</code> effects could alternatively be included as fixed effects (try it!). This will reduce <span class="math inline">\(V_R\)</span> and increase the estimates of heritability and repeatability, which must now be interpreted as proportions of phenotypic variance after conditioning on both age and year of measurement effects.</p>
<div class="sourceCode" id="cb624"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb624-1"><a href="asreml-r-2.html#cb624-1" aria-hidden="true"></a>modelz_<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">asreml</span>(</span>
<span id="cb624-2"><a href="asreml-r-2.html#cb624-2" aria-hidden="true"></a>  <span class="dt">fixed =</span> laydate <span class="op">~</span><span class="st"> </span>age <span class="op">+</span><span class="st"> </span>byear,</span>
<span id="cb624-3"><a href="asreml-r-2.html#cb624-3" aria-hidden="true"></a>  <span class="dt">random =</span> <span class="op">~</span><span class="st"> </span><span class="kw">vm</span>(animal, ainv) <span class="op">+</span><span class="st"> </span><span class="kw">ide</span>(animal) <span class="op">+</span></span>
<span id="cb624-4"><a href="asreml-r-2.html#cb624-4" aria-hidden="true"></a><span class="st">    </span>year,</span>
<span id="cb624-5"><a href="asreml-r-2.html#cb624-5" aria-hidden="true"></a>  <span class="dt">residual =</span> <span class="op">~</span><span class="st"> </span><span class="kw">idv</span>(units),</span>
<span id="cb624-6"><a href="asreml-r-2.html#cb624-6" aria-hidden="true"></a>  <span class="dt">data =</span> gryphonRM,</span>
<span id="cb624-7"><a href="asreml-r-2.html#cb624-7" aria-hidden="true"></a>  <span class="dt">na.action =</span> <span class="kw">na.method</span>(<span class="dt">x =</span> <span class="st">&quot;omit&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;omit&quot;</span>)</span>
<span id="cb624-8"><a href="asreml-r-2.html#cb624-8" aria-hidden="true"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 13 15:19:28 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4623.985           1.0   1569 15:19:28    0.0
##  2     -4063.535           1.0   1569 15:19:28    0.0
##  3     -3471.618           1.0   1569 15:19:28    0.0
##  4     -3105.972           1.0   1569 15:19:28    0.0
##  5     -2955.436           1.0   1569 15:19:28    0.0
##  6     -2934.435           1.0   1569 15:19:28    0.0
##  7     -2933.721           1.0   1569 15:19:28    0.0
##  8     -2933.720           1.0   1569 15:19:28    0.0</code></pre>
<div class="sourceCode" id="cb626"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb626-1"><a href="asreml-r-2.html#cb626-1" aria-hidden="true"></a><span class="kw">summary</span>(modelz_<span class="dv">3</span>)<span class="op">$</span>varcomp</span></code></pre></div>
<pre><code>##                  component std.error   z.ratio bound %ch
## year              8.029139 1.9920127  4.030666     P   0
## vm(animal, ainv)  5.060775 1.7855255  2.834334     P   0
## ide(animal)       8.412539 1.6494894  5.100087     P   0
## units!units       7.805139 0.3331474 23.428484     P   0
## units!R           1.000000        NA        NA     F   0</code></pre>
<div class="sourceCode" id="cb628"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb628-1"><a href="asreml-r-2.html#cb628-1" aria-hidden="true"></a><span class="kw">summary</span>(modelw, <span class="dt">coef =</span> <span class="ot">TRUE</span>)<span class="op">$</span>coef.fixed</span>
<span id="cb628-2"><a href="asreml-r-2.html#cb628-2" aria-hidden="true"></a><span class="kw">wald.asreml</span>(modelz_<span class="dv">3</span>, <span class="dt">ssType =</span> <span class="st">&quot;conditional&quot;</span>, <span class="dt">denDF =</span> <span class="st">&quot;numeric&quot;</span>)</span></code></pre></div>
<pre><code>##              solution std error   z.ratio
## age_2        0.000000        NA        NA
## age_3        2.577777 0.3355253  7.682811
## age_4        4.247276 0.3309028 12.835418
## age_5        6.094490 0.3375537 18.054872
## age_6        3.132675 0.3371074  9.292811
## (Intercept) 20.305073 0.2899515 70.029214</code></pre>
<pre><code>## Model fitted using the sigma parameterization.</code></pre>
<pre><code>## Warning in asreml(fixed = laydate ~ age + byear, random = ~vm(animal, ainv) + :
## Algebraic derivatives for denominator df not available.</code></pre>
<pre><code>## ASReml 4.1.0 Fri May 13 15:19:28 2022
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2933.720           1.0   1569 15:19:28    0.0
##  2     -2933.720           1.0   1569 15:19:28    0.0
## Calculating denominator DF</code></pre>
<pre><code>## 
##             Df denDF   F.inc   F.con Margin      Pr
## (Intercept)  1  55.3 1894.00 1894.00        0.00000
## age          4 845.2  152.70  132.90      A 0.00000
## byear       33 466.5    0.77    0.77      A 0.81646</code></pre>
<!-- C2  What to do more , may be extrac BLUP also !-->

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scenario-and-data-2.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="gremlin-3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/wam_tuto/edit/master/04_01-rep_asreml.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["wam_tuto.pdf", "wam_tuto.epub", "wam_tuto.mobi"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toc_depth": 4
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
