<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>3.2 Asreml-R | How to fit an animal model</title>
  <meta name="description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="3.2 Asreml-R | How to fit an animal model" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/images/missing.png" />
  <meta property="og:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="github-repo" content="JulienGAMartin/wam_tuto" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3.2 Asreml-R | How to fit an animal model" />
  
  <meta name="twitter:description" content="Updated and extended tutorials from An ecologist guide to animal model (Wilson et al. 2010)" />
  <meta name="twitter:image" content="/images/missing.png" />

<meta name="author" content="Julien Martin" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scenario-and-data-1.html"/>
<link rel="next" href="gremlin-2.html"/>
<script src="libs/header-attrs-2.8/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="css/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">How to fit an animal model</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#contributors"><i class="fa fa-check"></i>Contributors</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>1.1</b> Data</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="data.html"><a href="data.html#data-files"><i class="fa fa-check"></i><b>1.1.1</b> Data files</a></li>
<li class="chapter" data-level="1.1.2" data-path="data.html"><a href="data.html#notes-on-data-and-pedigree"><i class="fa fa-check"></i><b>1.1.2</b> Notes on data and pedigree</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>1.2</b> R</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="r.html"><a href="r.html#r-packages"><i class="fa fa-check"></i><b>1.2.1</b> R packages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="univariate-animal-model.html"><a href="univariate-animal-model.html"><i class="fa fa-check"></i><b>2</b> Univariate animal model</a>
<ul>
<li class="chapter" data-level="2.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html"><i class="fa fa-check"></i><b>2.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="scenario-and-data.html"><a href="scenario-and-data.html#scenario"><i class="fa fa-check"></i><b>2.1.1</b> Scenario</a></li>
<li class="chapter" data-level="2.1.2" data-path="scenario-and-data.html"><a href="scenario-and-data.html#data-files-1"><i class="fa fa-check"></i><b>2.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html"><i class="fa fa-check"></i><b>2.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="asreml-r-1.html"><a href="asreml-r-1.html#running-the-model"><i class="fa fa-check"></i><b>2.2.1</b> Running the model</a></li>
<li class="chapter" data-level="2.2.2" data-path="asreml-r-1.html"><a href="asreml-r-1.html#estimating-heritability"><i class="fa fa-check"></i><b>2.2.2</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.2.3" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-fixed-effects"><i class="fa fa-check"></i><b>2.2.3</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.2.4" data-path="asreml-r-1.html"><a href="asreml-r-1.html#adding-random-effects"><i class="fa fa-check"></i><b>2.2.4</b> Adding random effects</a></li>
<li class="chapter" data-level="2.2.5" data-path="asreml-r-1.html"><a href="asreml-r-1.html#testing-significance-of-random-effects"><i class="fa fa-check"></i><b>2.2.5</b> Testing significance of random effects</a></li>
<li class="chapter" data-level="2.2.6" data-path="asreml-r-1.html"><a href="asreml-r-1.html#further-partitioning-the-variance"><i class="fa fa-check"></i><b>2.2.6</b> Further partitioning the variance</a></li>
<li class="chapter" data-level="2.2.7" data-path="asreml-r-1.html"><a href="asreml-r-1.html#modification-of-model-parameter"><i class="fa fa-check"></i><b>2.2.7</b> Modification of model parameter</a></li>
<li class="chapter" data-level="2.2.8" data-path="asreml-r-1.html"><a href="asreml-r-1.html#covariance-between-two-random-effects"><i class="fa fa-check"></i><b>2.2.8</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="gremlin-1.html"><a href="gremlin-1.html"><i class="fa fa-check"></i><b>2.3</b> gremlin</a></li>
<li class="chapter" data-level="2.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html"><i class="fa fa-check"></i><b>2.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#running-the-model-1"><i class="fa fa-check"></i><b>2.4.1</b> Running the model</a></li>
<li class="chapter" data-level="2.4.2" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#change-in-iteration-and-sampling"><i class="fa fa-check"></i><b>2.4.2</b> Change in iteration and sampling</a></li>
<li class="chapter" data-level="2.4.3" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#change-priors-parameters"><i class="fa fa-check"></i><b>2.4.3</b> Change priors parameters</a></li>
<li class="chapter" data-level="2.4.4" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#estimating-heritability-1"><i class="fa fa-check"></i><b>2.4.4</b> Estimating heritability</a></li>
<li class="chapter" data-level="2.4.5" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-fixed-effects-1"><i class="fa fa-check"></i><b>2.4.5</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.4.6" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#adding-random-effects-1"><i class="fa fa-check"></i><b>2.4.6</b> Adding random effects</a></li>
<li class="chapter" data-level="2.4.7" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#testing-significance-of-variance-components"><i class="fa fa-check"></i><b>2.4.7</b> Testing significance of variance components</a></li>
<li class="chapter" data-level="2.4.8" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#further-partitioning-variance"><i class="fa fa-check"></i><b>2.4.8</b> Further partitioning variance</a></li>
<li class="chapter" data-level="2.4.9" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#modification-of-model-parameter-1"><i class="fa fa-check"></i><b>2.4.9</b> Modification of model parameter</a></li>
<li class="chapter" data-level="2.4.10" data-path="mcmcglmm-1.html"><a href="mcmcglmm-1.html#covariance-between-two-random-effects-1"><i class="fa fa-check"></i><b>2.4.10</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="brms-1.html"><a href="brms-1.html"><i class="fa fa-check"></i><b>2.5</b> brms</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="brms-1.html"><a href="brms-1.html#running-the-model-2"><i class="fa fa-check"></i><b>2.5.1</b> Running the model</a></li>
<li class="chapter" data-level="2.5.2" data-path="brms-1.html"><a href="brms-1.html#adding-fixed-effects-2"><i class="fa fa-check"></i><b>2.5.2</b> Adding fixed effects</a></li>
<li class="chapter" data-level="2.5.3" data-path="brms-1.html"><a href="brms-1.html#adding-random-effects-2"><i class="fa fa-check"></i><b>2.5.3</b> Adding random effects</a></li>
<li class="chapter" data-level="2.5.4" data-path="brms-1.html"><a href="brms-1.html#testing-significance-of-variance-components-1"><i class="fa fa-check"></i><b>2.5.4</b> Testing significance of variance components</a></li>
<li class="chapter" data-level="2.5.5" data-path="brms-1.html"><a href="brms-1.html#further-partitioning-of-the-variance"><i class="fa fa-check"></i><b>2.5.5</b> Further partitioning of the variance</a></li>
<li class="chapter" data-level="2.5.6" data-path="brms-1.html"><a href="brms-1.html#modification-of-model-parameter-2"><i class="fa fa-check"></i><b>2.5.6</b> Modification of model parameter</a></li>
<li class="chapter" data-level="2.5.7" data-path="brms-1.html"><a href="brms-1.html#covariance-between-two-random-effects-2"><i class="fa fa-check"></i><b>2.5.7</b> Covariance between two random effects</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="stan.html"><a href="stan.html"><i class="fa fa-check"></i><b>2.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="multivariate-animal-model.html"><a href="multivariate-animal-model.html"><i class="fa fa-check"></i><b>3</b> Multivariate animal model</a>
<ul>
<li class="chapter" data-level="3.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html"><i class="fa fa-check"></i><b>3.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#scenario-1"><i class="fa fa-check"></i><b>3.1.1</b> Scenario</a></li>
<li class="chapter" data-level="3.1.2" data-path="scenario-and-data-1.html"><a href="scenario-and-data-1.html#gryphon-files"><i class="fa fa-check"></i><b>3.1.2</b> gryphon files</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="asreml-biv.html"><a href="asreml-biv.html"><i class="fa fa-check"></i><b>3.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="asreml-biv.html"><a href="asreml-biv.html#running-the-model-3"><i class="fa fa-check"></i><b>3.2.1</b> Running the model</a></li>
<li class="chapter" data-level="3.2.2" data-path="asreml-biv.html"><a href="asreml-biv.html#adding-fixed-and-random-effects"><i class="fa fa-check"></i><b>3.2.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.2.3" data-path="asreml-biv.html"><a href="asreml-biv.html#significance-testing"><i class="fa fa-check"></i><b>3.2.3</b> Significance testing</a></li>
<li class="chapter" data-level="3.2.4" data-path="asreml-biv.html"><a href="asreml-biv.html#estimate-directly-the-genetic-correlation-within-the-model"><i class="fa fa-check"></i><b>3.2.4</b> Estimate directly the genetic correlation within the model</a></li>
<li class="chapter" data-level="3.2.5" data-path="asreml-biv.html"><a href="asreml-biv.html#partitionning-covariance-between-groups"><i class="fa fa-check"></i><b>3.2.5</b> Partitionning (co)variance between groups</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="gremlin-2.html"><a href="gremlin-2.html"><i class="fa fa-check"></i><b>3.3</b> gremlin</a></li>
<li class="chapter" data-level="3.4" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html"><i class="fa fa-check"></i><b>3.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#fitting-the-model"><i class="fa fa-check"></i><b>3.4.1</b> Fitting the model</a></li>
<li class="chapter" data-level="3.4.2" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#adding-fixed-and-random-effects-1"><i class="fa fa-check"></i><b>3.4.2</b> Adding fixed and random effects</a></li>
<li class="chapter" data-level="3.4.3" data-path="mcmcglmm-2.html"><a href="mcmcglmm-2.html#partitioning-covariances"><i class="fa fa-check"></i><b>3.4.3</b> Partitioning (co)variances</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="brms-2.html"><a href="brms-2.html"><i class="fa fa-check"></i><b>3.5</b> brms</a></li>
<li class="chapter" data-level="3.6" data-path="stan-1.html"><a href="stan-1.html"><i class="fa fa-check"></i><b>3.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="rep-measures.html"><a href="rep-measures.html"><i class="fa fa-check"></i><b>4</b> A repeated measures animal model</a>
<ul>
<li class="chapter" data-level="4.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html"><i class="fa fa-check"></i><b>4.1</b> Scenario and data</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#scenario-2"><i class="fa fa-check"></i><b>4.1.1</b> scenario</a></li>
<li class="chapter" data-level="4.1.2" data-path="scenario-and-data-2.html"><a href="scenario-and-data-2.html#data-files-2"><i class="fa fa-check"></i><b>4.1.2</b> Data files</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html"><i class="fa fa-check"></i><b>4.2</b> Asreml-R</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="asreml-r-2.html"><a href="asreml-r-2.html#estimating-repeatability"><i class="fa fa-check"></i><b>4.2.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.2.2" data-path="asreml-r-2.html"><a href="asreml-r-2.html#partitioning-additive-and-permanent-environment-effects"><i class="fa fa-check"></i><b>4.2.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.2.3" data-path="asreml-r-2.html"><a href="asreml-r-2.html#adding-additional-effects-and-testing-significance"><i class="fa fa-check"></i><b>4.2.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="gremlin-3.html"><a href="gremlin-3.html"><i class="fa fa-check"></i><b>4.3</b> gremlin</a></li>
<li class="chapter" data-level="4.4" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html"><i class="fa fa-check"></i><b>4.4</b> MCMCglmm</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#estimating-repeatability-1"><i class="fa fa-check"></i><b>4.4.1</b> Estimating repeatability</a></li>
<li class="chapter" data-level="4.4.2" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#partitioning-additive-and-permanent-environment-effects-1"><i class="fa fa-check"></i><b>4.4.2</b> Partitioning additive and permanent environment effects</a></li>
<li class="chapter" data-level="4.4.3" data-path="mcmcglmm-3.html"><a href="mcmcglmm-3.html#adding-additional-effects-and-testing-significance-1"><i class="fa fa-check"></i><b>4.4.3</b> Adding additional effects and testing significance</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="brms-3.html"><a href="brms-3.html"><i class="fa fa-check"></i><b>4.5</b> brms</a></li>
<li class="chapter" data-level="4.6" data-path="stan-2.html"><a href="stan-2.html"><i class="fa fa-check"></i><b>4.6</b> stan</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quick-comparison-of-codes.html"><a href="quick-comparison-of-codes.html"><i class="fa fa-check"></i><b>5</b> Quick comparison of codes</a>
<ul>
<li class="chapter" data-level="5.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html"><i class="fa fa-check"></i><b>5.1</b> Univariate model with repeated measures</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#asreml-r-3"><i class="fa fa-check"></i><b>5.1.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.1.2" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#gremlin-4"><i class="fa fa-check"></i><b>5.1.2</b> gremlin</a></li>
<li class="chapter" data-level="5.1.3" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#mcmcglmm-4"><i class="fa fa-check"></i><b>5.1.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.1.4" data-path="univariate-model-with-repeated-measures.html"><a href="univariate-model-with-repeated-measures.html#brms-4"><i class="fa fa-check"></i><b>5.1.4</b> brms</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="bivariate-model.html"><a href="bivariate-model.html"><i class="fa fa-check"></i><b>5.2</b> bivariate model</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="bivariate-model.html"><a href="bivariate-model.html#asreml-r-4"><i class="fa fa-check"></i><b>5.2.1</b> Asreml-R</a></li>
<li class="chapter" data-level="5.2.2" data-path="bivariate-model.html"><a href="bivariate-model.html#gremlin-5"><i class="fa fa-check"></i><b>5.2.2</b> gremlin</a></li>
<li class="chapter" data-level="5.2.3" data-path="bivariate-model.html"><a href="bivariate-model.html#mcmcglmm-5"><i class="fa fa-check"></i><b>5.2.3</b> MCMCglmm</a></li>
<li class="chapter" data-level="5.2.4" data-path="bivariate-model.html"><a href="bivariate-model.html#brms-5"><i class="fa fa-check"></i><b>5.2.4</b> brms</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">How to fit an animal model</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="asreml-biv" class="section level2" number="3.2">
<h2><span class="header-section-number">3.2</span> Asreml-R</h2>
<div id="running-the-model-3" class="section level3" number="3.2.1">
<h3><span class="header-section-number">3.2.1</span> Running the model</h3>
<p>First we need to load the <code>asreml</code> library:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="asreml-biv.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(asreml)</span></code></pre></div>
<p>For running multivariate analyses in ASReml-R, the code is slightly more complex than for the univariate case. This is because ASReml-R allows us to make different assumptions about the way in which traits might be related. So we need to explicitly code a model of the (co)variance structure we want to fit by specified some starting values. These are can be very approximate <em>guestimates</em>, but having reasonable starting values can aid convergence. Finally, we have increased the default maximum number of iterations (<code>maxiter</code>) which can help to achieve convergence for more complicated models. Another way to increase the number of iteration will be to use the <code>update</code> function. Notes that if the <code>LogLik</code> is not stabilized after several iterations, it is good indication of the model require more iteration.</p>
<p>It is also possible to let the model running without any specify starting values but usually univariate model will allow to get some <em>guestimates</em> in the additive genetic variances.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="asreml-biv.html#cb159-1" aria-hidden="true" tabindex="-1"></a>ainv <span class="ot">&lt;-</span> <span class="fu">ainverse</span>(gryphonped)</span>
<span id="cb159-2"><a href="asreml-biv.html#cb159-2" aria-hidden="true" tabindex="-1"></a>modela <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb159-3"><a href="asreml-biv.html#cb159-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait,</span>
<span id="cb159-4"><a href="asreml-biv.html#cb159-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">us</span>(trait)<span class="sc">:</span><span class="fu">vm</span>(animal, ainv), <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>),</span>
<span id="cb159-5"><a href="asreml-biv.html#cb159-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb159-6"><a href="asreml-biv.html#cb159-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb159-7"><a href="asreml-biv.html#cb159-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb159-8"><a href="asreml-biv.html#cb159-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb159-9"><a href="asreml-biv.html#cb159-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:54 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -5118.122           1.0   1535 10:22:54    0.0
##  2     -4358.769           1.0   1535 10:22:54    0.0
##  3     -3540.792           1.0   1535 10:22:54    0.0
##  4     -3004.970           1.0   1535 10:22:54    0.0
##  5     -2747.831           1.0   1535 10:22:54    0.0
##  6     -2687.807           1.0   1535 10:22:54    0.0
##  7     -2680.057           1.0   1535 10:22:54    0.0
##  8     -2679.743           1.0   1535 10:22:54    0.0
##  9     -2679.741           1.0   1535 10:22:54    0.0</code></pre>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="asreml-biv.html#cb161-1" aria-hidden="true" tabindex="-1"></a>modela <span class="ot">&lt;-</span> <span class="fu">update</span>(modela)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:54 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2679.741           1.0   1535 10:22:54    0.0
##  2     -2679.741           1.0   1535 10:22:54    0.0</code></pre>
<p><code>modela</code> has fitted a bivariate model of <code>bwt</code> and <code>tarsus</code>, with the mean for each of the traits as a fixed effect (<code>trait</code>). The additive genetic variance-covariance matrix (<span class="math inline">\(\textbf{G}\)</span>) is unstructured (<code>us</code>; <em>i.e.</em> all elements are free to vary) and the starting values for <span class="math inline">\(V_A\)</span> for <code>bwt</code>, <span class="math inline">\(COV_A\)</span> between <code>bwt</code> and <code>tarsus</code>, and <span class="math inline">\(V_A\)</span> for <code>tarsus</code> are set to 1, 0.1 and 1, respectively. Similarly, the residual matrix is unstructured and uses the same starting values.</p>
<p>Note that the argument <code>na.action = na.method(x = "include", y = "include")</code> can be add to the model.In a bivariate model, it will help calculate the covariance between two traits with different missing information <code>NA</code> and so help imbalance phenotypage and save sample size. However, it is important to scale ( mean =0, var =1) the two traits to correctly adjust the model(see Asreml-R manual for more information).
For the example, no missing information are present in the dataset.</p>
<p>Let’s have a look at the variance components, and notice that there are now seven (co)variance components reported in the table:</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="asreml-biv.html#cb163-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modela)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                                            component std.error  z.ratio bound
## trait:vm(animal, ainv)!trait_bwt:bwt        3.368405 0.6348356 5.305948     P
## trait:vm(animal, ainv)!trait_tarsus:bwt     2.459827 1.0732809 2.291876     P
## trait:vm(animal, ainv)!trait_tarsus:tarsus 12.345849 3.0744787 4.015591     P
## units:trait!R                               1.000000        NA       NA     F
## units:trait!trait_bwt:bwt                   3.849910 0.5200095 7.403539     P
## units:trait!trait_tarsus:bwt                3.313269 0.9129222 3.629300     P
## units:trait!trait_tarsus:tarsus            17.646386 2.6670308 6.616491     P
##                                            %ch
## trait:vm(animal, ainv)!trait_bwt:bwt         0
## trait:vm(animal, ainv)!trait_tarsus:bwt      0
## trait:vm(animal, ainv)!trait_tarsus:tarsus   0
## units:trait!R                                0
## units:trait!trait_bwt:bwt                    0
## units:trait!trait_tarsus:bwt                 0
## units:trait!trait_tarsus:tarsus              0</code></pre>
<p>The first three terms are related to the genetic matrix and, in order are <span class="math inline">\(V_{A,bwt}\)</span>, <span class="math inline">\(COV_A\)</span>, <span class="math inline">\(V_{A, tarsus}\)</span>. Below is again a line where the <code>units:traitr!R</code> component equals to 1, which again can be ignored. The final three terms relate to the residual matrix and correspond to <span class="math inline">\(V_{R,bwt}\)</span>, <span class="math inline">\(COV_R\)</span>, <span class="math inline">\(V_{R,tarsus}\)</span>. Based on our quick and dirty check (is <code>z.ratio</code> &gt; 1.96?) all components look to be statistically significant.</p>
<p>We can calculate the genetic correlation as <span class="math inline">\(COV_A / \sqrt{V_{A,bwt} \cdot V_{A,tarsus}}\)</span>. Thus this model gives an estimate of <span class="math inline">\(r_A\)</span> = 0.38. It is also possible to estimate the residual correlation <span class="math inline">\(r_res\)</span> = 0.4.</p>
<!-- Should we add an explication of the nature of the residual correlation or genetic correlation no? -->
<p>Although we can calculate this by hand, we can also use <code>vpredict()</code>, which also provides an (approximate) standard error:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="asreml-biv.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modela, r_A <span class="sc">~</span> V2 <span class="sc">/</span> <span class="fu">sqrt</span>(V1 <span class="sc">*</span> V3))</span></code></pre></div>
<pre><code>##     Estimate        SE
## r_A 0.381445 0.1299765</code></pre>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="asreml-biv.html#cb167-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modela, r_res <span class="sc">~</span> V6 <span class="sc">/</span> <span class="fu">sqrt</span>(V5 <span class="sc">*</span> V7))</span></code></pre></div>
<pre><code>##        Estimate         SE
## r_res 0.4019791 0.08607119</code></pre>
<p>Of course we can also calculate the heritability of <code>bwt</code> and <code>tarsus</code> from this model:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="asreml-biv.html#cb169-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modela, h2.bwt <span class="sc">~</span> V1 <span class="sc">/</span> (V1 <span class="sc">+</span> V5))</span></code></pre></div>
<pre><code>##         Estimate         SE
## h2.bwt 0.4666469 0.07671563</code></pre>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="asreml-biv.html#cb171-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modela, h2.tarsus <span class="sc">~</span> V3 <span class="sc">/</span> (V3 <span class="sc">+</span> V7))</span></code></pre></div>
<pre><code>##            Estimate         SE
## h2.tarsus 0.4116348 0.09305947</code></pre>
</div>
<div id="adding-fixed-and-random-effects" class="section level3" number="3.2.2">
<h3><span class="header-section-number">3.2.2</span> Adding fixed and random effects</h3>
<p>Fixed and random effects can be added just as for the univariate case. Given that our full model of bwt from tutorial 1 had sex as a fixed effect as well as birth year and mother as random effects, we could specify a bivariate formulation with the same complexity:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="asreml-biv.html#cb173-1" aria-hidden="true" tabindex="-1"></a>modelb <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb173-2"><a href="asreml-biv.html#cb173-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb173-3"><a href="asreml-biv.html#cb173-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb173-4"><a href="asreml-biv.html#cb173-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb173-5"><a href="asreml-biv.html#cb173-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb173-6"><a href="asreml-biv.html#cb173-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb173-7"><a href="asreml-biv.html#cb173-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb173-8"><a href="asreml-biv.html#cb173-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb173-9"><a href="asreml-biv.html#cb173-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb173-10"><a href="asreml-biv.html#cb173-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:54 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4672.301           1.0   1533 10:22:55    0.1
##  2     -4005.615           1.0   1533 10:22:55    0.0
##  3     -3271.483           1.0   1533 10:22:55    0.0 (1 restrained)
##  4     -2761.414           1.0   1533 10:22:55    0.0 (1 restrained)
##  5     -2481.357           1.0   1533 10:22:55    0.0
##  6     -2395.858           1.0   1533 10:22:55    0.0
##  7     -2381.050           1.0   1533 10:22:55    0.0
##  8     -2380.251           1.0   1533 10:22:55    0.0
##  9     -2380.246           1.0   1533 10:22:55    0.0</code></pre>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="asreml-biv.html#cb175-1" aria-hidden="true" tabindex="-1"></a>modelb <span class="ot">&lt;-</span> <span class="fu">update</span>(modelb)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:55 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2380.246           1.0   1533 10:22:55    0.1
##  2     -2380.246           1.0   1533 10:22:55    0.1</code></pre>
<p>Note that we have specified a covariance structure for each random effect and an estimate of the effect of sex on both birth weight and tarsus length.
<!-- trait:sex actually combined the effect of sex on both trait in the wald test, so I change it for at(trait): --></p>
<p>There will now be thirteen (co)variance components reported after running the code:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="asreml-biv.html#cb177-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelb)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                                             component std.error    z.ratio
## trait:byear!trait_bwt:bwt                   0.9746385 0.2825727  3.4491602
## trait:byear!trait_tarsus:bwt                0.1624076 0.4185079  0.3880635
## trait:byear!trait_tarsus:tarsus             3.7383721 1.2065992  3.0982716
## trait:mother!trait_bwt:bwt                  1.1445184 0.2302182  4.9714512
## trait:mother!trait_tarsus:bwt              -1.5567306 0.4051848 -3.8420260
## trait:mother!trait_tarsus:tarsus            4.8206132 1.3201300  3.6516202
## trait:vm(animal, ainv)!trait_bwt:bwt        1.9893546 0.4410246  4.5107569
## trait:vm(animal, ainv)!trait_tarsus:bwt     3.3170404 0.9032323  3.6724110
## trait:vm(animal, ainv)!trait_tarsus:tarsus 10.2294887 2.8077066  3.6433610
## units:trait!R                               1.0000000        NA         NA
## units:trait!trait_bwt:bwt                   1.8443110 0.3443178  5.3564203
## units:trait!trait_tarsus:bwt                4.0142841 0.7412540  5.4155308
## units:trait!trait_tarsus:tarsus            12.4845955 2.2893363  5.4533690
##                                            bound %ch
## trait:byear!trait_bwt:bwt                      P   0
## trait:byear!trait_tarsus:bwt                   P   0
## trait:byear!trait_tarsus:tarsus                P   0
## trait:mother!trait_bwt:bwt                     P   0
## trait:mother!trait_tarsus:bwt                  P   0
## trait:mother!trait_tarsus:tarsus               P   0
## trait:vm(animal, ainv)!trait_bwt:bwt           P   0
## trait:vm(animal, ainv)!trait_tarsus:bwt        P   0
## trait:vm(animal, ainv)!trait_tarsus:tarsus     P   0
## units:trait!R                                  F   0
## units:trait!trait_bwt:bwt                      P   0
## units:trait!trait_tarsus:bwt                   P   0
## units:trait!trait_tarsus:tarsus                P   0</code></pre>
<p>we can estimate the different correlations using <code>vpredict</code>:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="asreml-biv.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modelb, r_byear <span class="sc">~</span> V2 <span class="sc">/</span> <span class="fu">sqrt</span>(V1 <span class="sc">*</span> V3))</span></code></pre></div>
<pre><code>##           Estimate        SE
## r_byear 0.08508312 0.2134209</code></pre>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="asreml-biv.html#cb181-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modelb, r_M <span class="sc">~</span> V5 <span class="sc">/</span> <span class="fu">sqrt</span>(V4 <span class="sc">*</span> V6))</span></code></pre></div>
<pre><code>##       Estimate        SE
## r_M -0.6627518 0.2487963</code></pre>
<div class="sourceCode" id="cb183"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb183-1"><a href="asreml-biv.html#cb183-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modelb, r_A <span class="sc">~</span> V8 <span class="sc">/</span> <span class="fu">sqrt</span>(V7 <span class="sc">*</span> V9))</span></code></pre></div>
<pre><code>##      Estimate        SE
## r_A 0.7353053 0.1094747</code></pre>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="asreml-biv.html#cb185-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(modelb, r_res <span class="sc">~</span> V12 <span class="sc">/</span> <span class="fu">sqrt</span>(V11 <span class="sc">*</span> V13))</span></code></pre></div>
<pre><code>##        Estimate         SE
## r_res 0.8365729 0.07366762</code></pre>
<p>Now we can look at the fixed effects parameters and assess their significance with a conditional Wald F-test:</p>
<div class="sourceCode" id="cb187"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb187-1"><a href="asreml-biv.html#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelb, <span class="at">coef =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>coef.fi</span>
<span id="cb187-2"><a href="asreml-biv.html#cb187-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.asreml</span>(modelb, <span class="at">denDF =</span> <span class="st">&quot;default&quot;</span>, <span class="at">ssType =</span> <span class="st">&quot;conditional&quot;</span>)<span class="sc">$</span>Wald</span></code></pre></div>
<pre><code>##                           solution std error    z.ratio
## at(trait, tarsus):sex_1  0.0000000        NA         NA
## at(trait, tarsus):sex_2 -0.0684413 0.3823448 -0.1790041
## at(trait, bwt):sex_1     0.0000000        NA         NA
## at(trait, bwt):sex_2     1.9502053 0.1480467 13.1729086
## trait_bwt                6.3844483 0.2328210 27.4221324
## trait_tarsus            20.5936436 0.5098944 40.3880569</code></pre>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:55 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2380.246           1.0   1533 10:22:55    0.1
##  2     -2380.246           1.0   1533 10:22:56    0.0
## Calculating denominator DF</code></pre>
<pre><code>## 
##                       Df denDF   F.inc   F.con Margin      Pr
## trait                  2  52.6 1396.00 1396.00        0.00000
## at(trait, bwt):sex     1 812.8  298.40  173.50      B 0.00000
## at(trait, tarsus):sex  1 747.9    0.03    0.03      B 0.85798</code></pre>
<p>Note that it is possible to specify a fixed effect to a specific trait by adding the number of order within <code>cbind</code> inside the argument <code>at(trait,x)</code>. For example, here we apply the fixed effect <code>sex</code> only to the response variable <code>tarsus</code>.</p>
<div class="sourceCode" id="cb191"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb191-1"><a href="asreml-biv.html#cb191-1" aria-hidden="true" tabindex="-1"></a>modelb_2 <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb191-2"><a href="asreml-biv.html#cb191-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait, <span class="dv">2</span>)<span class="sc">:</span>sex,</span>
<span id="cb191-3"><a href="asreml-biv.html#cb191-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb191-4"><a href="asreml-biv.html#cb191-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb191-5"><a href="asreml-biv.html#cb191-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb191-6"><a href="asreml-biv.html#cb191-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb191-7"><a href="asreml-biv.html#cb191-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb191-8"><a href="asreml-biv.html#cb191-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb191-9"><a href="asreml-biv.html#cb191-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb191-10"><a href="asreml-biv.html#cb191-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:56 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4810.563           1.0   1534 10:22:56    0.1
##  2     -4129.799           1.0   1534 10:22:56    0.0
##  3     -3382.529           1.0   1534 10:22:56    0.0 (1 restrained)
##  4     -2864.076           1.0   1534 10:22:56    0.0
##  5     -2574.891           1.0   1534 10:22:56    0.0
##  6     -2478.879           1.0   1534 10:22:56    0.0
##  7     -2458.305           1.0   1534 10:22:56    0.0
##  8     -2456.425           1.0   1534 10:22:56    0.0
##  9     -2456.377           1.0   1534 10:22:56    0.0
## 10     -2456.376           1.0   1534 10:22:56    0.0</code></pre>
<div class="sourceCode" id="cb193"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb193-1"><a href="asreml-biv.html#cb193-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelb_2, <span class="at">coef =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>coef.fi</span>
<span id="cb193-2"><a href="asreml-biv.html#cb193-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.asreml</span>(modelb_2, <span class="at">denDF =</span> <span class="st">&quot;default&quot;</span>, <span class="at">ssType =</span> <span class="st">&quot;conditional&quot;</span>)<span class="sc">$</span>Wald</span></code></pre></div>
<pre><code>##                          solution std error   z.ratio
## at(trait, tarsus):sex_1  0.000000        NA        NA
## at(trait, tarsus):sex_2 -3.267042 0.2953279 -11.06242
## trait_bwt                7.636226 0.2389515  31.95722
## trait_tarsus            22.703658 0.4827348  47.03133</code></pre>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:56 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2456.376           1.0   1534 10:22:57    0.1
##  2     -2456.376           1.0   1534 10:22:57    0.0
## Calculating denominator DF</code></pre>
<pre><code>## 
##                       Df denDF  F.inc  F.con Margin          Pr
## trait                  2  50.7 1233.0 1233.0        0.00000e+00
## at(trait, tarsus):sex  1 522.9  122.4  122.4      B 1.02886e-25</code></pre>
</div>
<div id="significance-testing" class="section level3" number="3.2.3">
<h3><span class="header-section-number">3.2.3</span> Significance testing</h3>
<p>Under the model above <span class="math inline">\(r_M\)</span> is estimated as -0.66 and the <code>z.ratio</code> associated with the corresponding covariance (<span class="math inline">\(COV_M\)</span>) is &gt;2 (in absolute terms). We might therefore infer that there is evidence for a strong negative correlation between the traits with respect to the mother and that while maternal identity explains variance in both traits those mothers that tend to produce heavier offspring actually tend to produce offspring with shorter tarsus lengths.</p>
<p>To formally test if <span class="math inline">\(COV_M\)</span> is significantly different from zero, we can compare the log-likelihood for this model:</p>
<div class="sourceCode" id="cb197"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb197-1"><a href="asreml-biv.html#cb197-1" aria-hidden="true" tabindex="-1"></a>modelb<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2380.246</code></pre>
<p>to a model in which we specify that <span class="math inline">\(COV_M\)</span>=0. Since this constraint reduces the number of parameters to be estimated by one, we can use a likelihood ratio test (LRT) with one degree of freedom. To run the constrained model, we modify the G structure defined for the <code>mother</code> random effect to diagonal (<code>diag</code>), which means we only estimate the variances (the diagonal of the matrix) but not the covariance (the covariance are fixed to 0):</p>
<div class="sourceCode" id="cb199"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb199-1"><a href="asreml-biv.html#cb199-1" aria-hidden="true" tabindex="-1"></a>modelc <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb199-2"><a href="asreml-biv.html#cb199-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb199-3"><a href="asreml-biv.html#cb199-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb199-4"><a href="asreml-biv.html#cb199-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb199-5"><a href="asreml-biv.html#cb199-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">diag</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb199-6"><a href="asreml-biv.html#cb199-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb199-7"><a href="asreml-biv.html#cb199-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb199-8"><a href="asreml-biv.html#cb199-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb199-9"><a href="asreml-biv.html#cb199-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb199-10"><a href="asreml-biv.html#cb199-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:57 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4677.820           1.0   1533 10:22:57    0.1
##  2     -4010.442           1.0   1533 10:22:57    0.0
##  3     -3275.409           1.0   1533 10:22:57    0.0
##  4     -2763.519           1.0   1533 10:22:57    0.0
##  5     -2483.732           1.0   1533 10:22:57    0.0
##  6     -2400.242           1.0   1533 10:22:57    0.0
##  7     -2386.663           1.0   1533 10:22:57    0.0
##  8     -2386.049           1.0   1533 10:22:57    0.0
##  9     -2386.045           1.0   1533 10:22:57    0.0</code></pre>
<p>You can run <code>summary(modelc)$varcomp</code> to confirm this worked. We can now obtain the log-likelihood of this model and compare this to that of <code>modelb</code> using a likelihood ratio test:</p>
<div class="sourceCode" id="cb201"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb201-1"><a href="asreml-biv.html#cb201-1" aria-hidden="true" tabindex="-1"></a>modelc<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2386.045</code></pre>
<p>We can see that the model log-likelihood is now -2386.05.
And comparing the models using a likelihood ratio test:</p>
<div class="sourceCode" id="cb203"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb203-1"><a href="asreml-biv.html#cb203-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (modelb<span class="sc">$</span>loglik <span class="sc">-</span> modelc<span class="sc">$</span>loglik)</span></code></pre></div>
<pre><code>## [1] 11.59835</code></pre>
<p>So our chi-square test statistic is <span class="math inline">\(\chi^2_1\)</span>= 11.6.
The p-value that goes with this is obtained by:</p>
<div class="sourceCode" id="cb205"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb205-1"><a href="asreml-biv.html#cb205-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (modelb<span class="sc">$</span>loglik <span class="sc">-</span> modelc<span class="sc">$</span>loglik), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.0006601037</code></pre>
<p>We would therefore conclude that the maternal covariance is significantly different from zero.</p>
<p>We could apply the same procedure to show that the residual (environmental) covariance and the genetic covariance estimates are significantly greater than zero (<em>i.e.</em>, heavier individuals tend to have longer tarsus lengths). In contrast, we should find that the byear covariance between the two traits is non-significant.</p>
<div class="sourceCode" id="cb207"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb207-1"><a href="asreml-biv.html#cb207-1" aria-hidden="true" tabindex="-1"></a>modeld <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb207-2"><a href="asreml-biv.html#cb207-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb207-3"><a href="asreml-biv.html#cb207-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb207-4"><a href="asreml-biv.html#cb207-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">diag</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb207-5"><a href="asreml-biv.html#cb207-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb207-6"><a href="asreml-biv.html#cb207-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb207-7"><a href="asreml-biv.html#cb207-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb207-8"><a href="asreml-biv.html#cb207-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb207-9"><a href="asreml-biv.html#cb207-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb207-10"><a href="asreml-biv.html#cb207-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:57 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -4672.708           1.0   1533 10:22:58    0.0
##  2     -4005.953           1.0   1533 10:22:58    0.0
##  3     -3271.737           1.0   1533 10:22:58    0.0 (1 restrained)
##  4     -2761.626           1.0   1533 10:22:58    0.0 (1 restrained)
##  5     -2481.649           1.0   1533 10:22:58    0.0
##  6     -2395.992           1.0   1533 10:22:58    0.0
##  7     -2381.136           1.0   1533 10:22:58    0.0
##  8     -2380.331           1.0   1533 10:22:58    0.0
##  9     -2380.326           1.0   1533 10:22:58    0.0</code></pre>
<div class="sourceCode" id="cb209"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb209-1"><a href="asreml-biv.html#cb209-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (modelb<span class="sc">$</span>loglik <span class="sc">-</span> modeld<span class="sc">$</span>loglik)</span></code></pre></div>
<pre><code>## [1] 0.1600641</code></pre>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="asreml-biv.html#cb211-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (modelb<span class="sc">$</span>loglik <span class="sc">-</span> modeld<span class="sc">$</span>loglik), <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## [1] 0.6890975</code></pre>
</div>
<div id="estimate-directly-the-genetic-correlation-within-the-model" class="section level3" number="3.2.4">
<h3><span class="header-section-number">3.2.4</span> Estimate directly the genetic correlation within the model</h3>
<p>Within Asreml-r, different matrix structure can be specify such as <code>us</code>,<code>corg</code>, <code>diag</code>, etc (cf see the Asreml-r guide). Instead of the fitting an unstructured matrix with the argument <code>us</code> or a reduced model with no covariance with the argument <code>diag</code>, we can also directly estimate the genetic correlation between the <code>bwt</code> and <code>tarsus</code> with <code>corgh</code>.
Here we decide to estimate directly the additive genetic correlation.</p>
<!-- I dont know if we can specify initial values with corgh !, i remove it -->
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="asreml-biv.html#cb213-1" aria-hidden="true" tabindex="-1"></a>modele <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb213-2"><a href="asreml-biv.html#cb213-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb213-3"><a href="asreml-biv.html#cb213-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">corgh</span>(trait)<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb213-4"><a href="asreml-biv.html#cb213-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb213-5"><a href="asreml-biv.html#cb213-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb213-6"><a href="asreml-biv.html#cb213-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb213-7"><a href="asreml-biv.html#cb213-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb213-8"><a href="asreml-biv.html#cb213-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb213-9"><a href="asreml-biv.html#cb213-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb213-10"><a href="asreml-biv.html#cb213-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:58 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -3544.356           1.0   1533 10:22:58    0.0
##  2     -3177.908           1.0   1533 10:22:58    0.0 (1 restrained)
##  3     -2784.992           1.0   1533 10:22:58    0.0
##  4     -2527.352           1.0   1533 10:22:58    0.0
##  5     -2406.422           1.0   1533 10:22:58    0.0
##  6     -2382.062           1.0   1533 10:22:58    0.0
##  7     -2380.263           1.0   1533 10:22:58    0.0
##  8     -2380.246           1.0   1533 10:22:58    0.0
##  9     -2380.246           1.0   1533 10:22:58    0.0</code></pre>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="asreml-biv.html#cb215-1" aria-hidden="true" tabindex="-1"></a>modele <span class="ot">&lt;-</span> <span class="fu">update</span>(modele)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:58 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2380.246           1.0   1533 10:22:58    0.1
##  2     -2380.246           1.0   1533 10:22:58    0.0</code></pre>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="asreml-biv.html#cb217-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                                                     component std.error
## trait:byear!trait_bwt:bwt                           0.9746376 0.2825690
## trait:byear!trait_tarsus:bwt                        0.1624052 0.4184989
## trait:byear!trait_tarsus:tarsus                     3.7383599 1.2065684
## trait:mother!trait_bwt:bwt                          1.1445196 0.2302189
## trait:mother!trait_tarsus:bwt                      -1.5567326 0.4051847
## trait:mother!trait_tarsus:tarsus                    4.8206100 1.3201239
## trait:vm(animal, ainv)!trait!tarsus:!trait!bwt.cor  0.7353034 0.1094744
## trait:vm(animal, ainv)!trait_bwt                    1.9893544 0.4410242
## trait:vm(animal, ainv)!trait_tarsus                10.2296667 2.8078190
## units:trait!R                                       1.0000000        NA
## units:trait!trait_bwt:bwt                           1.8443104 0.3443173
## units:trait!trait_tarsus:bwt                        4.0142731 0.7412587
## units:trait!trait_tarsus:tarsus                    12.4844745 2.2893621
##                                                      z.ratio bound %ch
## trait:byear!trait_bwt:bwt                           3.449203     P   0
## trait:byear!trait_tarsus:bwt                        0.388066     P   0
## trait:byear!trait_tarsus:tarsus                     3.098341     P   0
## trait:mother!trait_bwt:bwt                          4.971441     P   0
## trait:mother!trait_tarsus:bwt                      -3.842032     P   0
## trait:mother!trait_tarsus:tarsus                    3.651634     P   0
## trait:vm(animal, ainv)!trait!tarsus:!trait!bwt.cor  6.716668     U   0
## trait:vm(animal, ainv)!trait_bwt                    4.510760     P   0
## trait:vm(animal, ainv)!trait_tarsus                 3.643279     P   0
## units:trait!R                                             NA     F   0
## units:trait!trait_bwt:bwt                           5.356427     P   0
## units:trait!trait_tarsus:bwt                        5.415482     P   0
## units:trait!trait_tarsus:tarsus                     5.453255     P   0</code></pre>
<p>It is important to note that using <code>corgh</code> change the order of the estimate (co)variance. All different calculation need to be adjust in consequence.
It is also important to check the difference between the model with <code>us</code> and <code>corgh</code> to make sure any mistake are made.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="asreml-biv.html#cb219-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelb)<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2380.246</code></pre>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="asreml-biv.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modele)<span class="sc">$</span>loglik</span></code></pre></div>
<pre><code>## [1] -2380.246</code></pre>
<p>There two main advantages to use <code>corgh</code>: first, a direct estimation of correlation within the G matrix can avoid mistake in the <code>vpredict</code> calculation; second, it is possible to test if the correlation is significantly different than 0 (similar result as LRT with the covariance) but also to -1 and 1 which correspond of the correlation boundaries.
The following code showed how to create a reduced model with the correlation close to 1 and compared to the initial model.
Since we compared the correlation to its boundary, the degree of freedom is only half as a one tail LTR.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="asreml-biv.html#cb223-1" aria-hidden="true" tabindex="-1"></a>MODEL_MODIF <span class="ot">&lt;-</span> <span class="fu">update.asreml</span>(modele, <span class="at">start.values =</span> T)</span>
<span id="cb223-2"><a href="asreml-biv.html#cb223-2" aria-hidden="true" tabindex="-1"></a>G_MOD <span class="ot">&lt;-</span> MODEL_MODIF<span class="sc">$</span>vparameters.table[(<span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>), ]</span>
<span id="cb223-3"><a href="asreml-biv.html#cb223-3" aria-hidden="true" tabindex="-1"></a>G_MOD[<span class="dv">1</span>, <span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="fl">0.99999</span></span>
<span id="cb223-4"><a href="asreml-biv.html#cb223-4" aria-hidden="true" tabindex="-1"></a>G_MOD[<span class="dv">1</span>, <span class="dv">3</span>] <span class="ot">&lt;-</span> <span class="st">&quot;F&quot;</span></span>
<span id="cb223-5"><a href="asreml-biv.html#cb223-5" aria-hidden="true" tabindex="-1"></a>modele.red <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb223-6"><a href="asreml-biv.html#cb223-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb223-7"><a href="asreml-biv.html#cb223-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">corgh</span>(trait)<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb223-8"><a href="asreml-biv.html#cb223-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb223-9"><a href="asreml-biv.html#cb223-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb223-10"><a href="asreml-biv.html#cb223-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>)),</span>
<span id="cb223-11"><a href="asreml-biv.html#cb223-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb223-12"><a href="asreml-biv.html#cb223-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb223-13"><a href="asreml-biv.html#cb223-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span>,</span>
<span id="cb223-14"><a href="asreml-biv.html#cb223-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">G.param =</span> G_MOD</span>
<span id="cb223-15"><a href="asreml-biv.html#cb223-15" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Model fitted using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:59 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2545.227           1.0   1533 10:22:59    0.0
##  2     -2483.880           1.0   1533 10:22:59    0.0
##  3     -2423.502           1.0   1533 10:22:59    0.0
##  4     -2392.508           1.0   1533 10:22:59    0.0
##  5     -2383.661           1.0   1533 10:22:59    0.0
##  6     -2383.084           1.0   1533 10:22:59    0.0
##  7     -2383.033           1.0   1533 10:22:59    0.0
##  8     -2383.022           1.0   1533 10:22:59    0.0
##  9     -2383.019           1.0   1533 10:22:59    0.0
## 10     -2383.019           1.0   1533 10:22:59    0.0</code></pre>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="asreml-biv.html#cb225-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span> <span class="sc">*</span> (modele<span class="sc">$</span>loglik <span class="sc">-</span> modele.red<span class="sc">$</span>loglik)</span></code></pre></div>
<pre><code>## [1] 5.544679</code></pre>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="asreml-biv.html#cb227-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">pchisq</span>(<span class="dv">2</span> <span class="sc">*</span> (modele<span class="sc">$</span>loglik <span class="sc">-</span> modele.red<span class="sc">$</span>loglik), <span class="at">df =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<pre><code>## [1] 0.006598675</code></pre>
</div>
<div id="partitionning-covariance-between-groups" class="section level3" number="3.2.5">
<h3><span class="header-section-number">3.2.5</span> Partitionning (co)variance between groups</h3>
<p>Similar to the univariate model, it is possible to partition the variance and also the covariance between different groups within the dataset. Here, we can estimate sex-specific genetic correlation.
Note, to partition a correlation, it is require to have important sample size within each group. For this example, we simplify the model !</p>
<!-- SAme her I don't know how to specify initial values so I remove it -->
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="asreml-biv.html#cb229-1" aria-hidden="true" tabindex="-1"></a>gryphon <span class="ot">&lt;-</span> gryphon[<span class="fu">order</span>(gryphon<span class="sc">$</span>sex), ]</span>
<span id="cb229-2"><a href="asreml-biv.html#cb229-2" aria-hidden="true" tabindex="-1"></a>model_sex <span class="ot">&lt;-</span> <span class="fu">asreml</span>(</span>
<span id="cb229-3"><a href="asreml-biv.html#cb229-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">fixed =</span> <span class="fu">cbind</span>(bwt, tarsus) <span class="sc">~</span> trait <span class="sc">+</span> <span class="fu">at</span>(trait)<span class="sc">:</span>sex,</span>
<span id="cb229-4"><a href="asreml-biv.html#cb229-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">random =</span> <span class="sc">~</span> <span class="fu">at</span>(sex)<span class="sc">:</span><span class="fu">us</span>(trait)<span class="sc">:</span><span class="fu">vm</span>(animal, ainv) <span class="sc">+</span></span>
<span id="cb229-5"><a href="asreml-biv.html#cb229-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>byear <span class="sc">+</span></span>
<span id="cb229-6"><a href="asreml-biv.html#cb229-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">us</span>(trait, <span class="at">init =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.1</span>, <span class="dv">1</span>))<span class="sc">:</span>mother,</span>
<span id="cb229-7"><a href="asreml-biv.html#cb229-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">residual =</span> <span class="sc">~</span> <span class="fu">dsum</span>(<span class="sc">~</span> <span class="fu">id</span>(units)<span class="sc">:</span><span class="fu">us</span>(trait) <span class="sc">|</span> sex),</span>
<span id="cb229-8"><a href="asreml-biv.html#cb229-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gryphon,</span>
<span id="cb229-9"><a href="asreml-biv.html#cb229-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">na.action =</span> <span class="fu">na.method</span>(<span class="at">x =</span> <span class="st">&quot;include&quot;</span>, <span class="at">y =</span> <span class="st">&quot;include&quot;</span>),</span>
<span id="cb229-10"><a href="asreml-biv.html#cb229-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxit =</span> <span class="dv">20</span></span>
<span id="cb229-11"><a href="asreml-biv.html#cb229-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## Multi-section model using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:22:59 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2495.853           1.0   1807 10:22:59    0.1 (1 restrained)
##  2     -2444.497           1.0   1807 10:22:59    0.1
##  3     -2401.367           1.0   1807 10:22:59    0.1
##  4     -2390.943           1.0   1807 10:23:00    0.1
##  5     -2388.819           1.0   1807 10:23:00    0.1
##  6     -2388.738           1.0   1807 10:23:00    0.1
##  7     -2388.736           1.0   1807 10:23:00    0.1</code></pre>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="asreml-biv.html#cb231-1" aria-hidden="true" tabindex="-1"></a>model_sex <span class="ot">&lt;-</span> <span class="fu">update</span>(model_sex)</span></code></pre></div>
<pre><code>## Multi-section model using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:23:00 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2388.736           1.0   1807 10:23:00    0.1
##  2     -2388.736           1.0   1807 10:23:00    0.1</code></pre>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="asreml-biv.html#cb233-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_sex)<span class="sc">$</span>varcomp</span></code></pre></div>
<pre><code>##                                                        component std.error
## trait:byear!trait_bwt:bwt                              0.9858502 0.2863930
## trait:byear!trait_tarsus:bwt                           0.1525073 0.4334219
## trait:byear!trait_tarsus:tarsus                        3.9981750 1.2798231
## trait:mother!trait_bwt:bwt                             1.3312802 0.2484496
## trait:mother!trait_tarsus:bwt                         -1.6173911 0.4283985
## trait:mother!trait_tarsus:tarsus                       4.7543015 1.3546795
## at(sex, 1):trait:vm(animal, ainv)!trait_bwt:bwt        1.3402726 0.5670807
## at(sex, 1):trait:vm(animal, ainv)!trait_tarsus:bwt     2.3607838 1.1348534
## at(sex, 1):trait:vm(animal, ainv)!trait_tarsus:tarsus  6.0624925 3.1304679
## at(sex, 2):trait:vm(animal, ainv)!trait_bwt:bwt        1.8645331 0.8887843
## at(sex, 2):trait:vm(animal, ainv)!trait_tarsus:bwt     5.0952433 2.0683128
## at(sex, 2):trait:vm(animal, ainv)!trait_tarsus:tarsus 14.9762227 6.4472652
## sex_1!R                                                1.0000000        NA
## sex_1!trait_bwt:bwt                                    2.3079924 0.5015700
## sex_1!trait_tarsus:bwt                                 4.4288323 1.0376540
## sex_1!trait_tarsus:tarsus                             13.4858721 2.9285483
## sex_2!R                                                1.0000000        NA
## sex_2!trait_bwt:bwt                                    1.7957128 0.7549623
## sex_2!trait_tarsus:bwt                                 2.6342177 1.7685005
## sex_2!trait_tarsus:tarsus                              9.6101885 5.4914087
##                                                          z.ratio bound %ch
## trait:byear!trait_bwt:bwt                              3.4422982     P 0.0
## trait:byear!trait_tarsus:bwt                           0.3518681     P 0.0
## trait:byear!trait_tarsus:tarsus                        3.1240060     P 0.0
## trait:mother!trait_bwt:bwt                             5.3583516     P 0.0
## trait:mother!trait_tarsus:bwt                         -3.7754356     P 0.0
## trait:mother!trait_tarsus:tarsus                       3.5095396     P 0.0
## at(sex, 1):trait:vm(animal, ainv)!trait_bwt:bwt        2.3634603     P 0.0
## at(sex, 1):trait:vm(animal, ainv)!trait_tarsus:bwt     2.0802544     P 0.0
## at(sex, 1):trait:vm(animal, ainv)!trait_tarsus:tarsus  1.9366091     P 0.0
## at(sex, 2):trait:vm(animal, ainv)!trait_bwt:bwt        2.0978466     P 0.0
## at(sex, 2):trait:vm(animal, ainv)!trait_tarsus:bwt     2.4634781     P 0.0
## at(sex, 2):trait:vm(animal, ainv)!trait_tarsus:tarsus  2.3228799     P 0.0
## sex_1!R                                                       NA     F 0.0
## sex_1!trait_bwt:bwt                                    4.6015360     P 0.0
## sex_1!trait_tarsus:bwt                                 4.2681204     P 0.0
## sex_1!trait_tarsus:tarsus                              4.6049683     P 0.0
## sex_2!R                                                       NA     F 0.0
## sex_2!trait_bwt:bwt                                    2.3785463     P 0.0
## sex_2!trait_tarsus:bwt                                 1.4895205     P 0.1
## sex_2!trait_tarsus:tarsus                              1.7500407     P 0.1</code></pre>
<p>we can estimate the different correlations using <code>vpredict</code>:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="asreml-biv.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_byear <span class="sc">~</span> V2 <span class="sc">/</span> <span class="fu">sqrt</span>(V1 <span class="sc">*</span> V3))</span></code></pre></div>
<pre><code>##           Estimate       SE
## r_byear 0.07681647 0.213139</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="asreml-biv.html#cb237-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_M <span class="sc">~</span> V5 <span class="sc">/</span> <span class="fu">sqrt</span>(V4 <span class="sc">*</span> V6))</span></code></pre></div>
<pre><code>##       Estimate        SE
## r_M -0.6428904 0.2489498</code></pre>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="asreml-biv.html#cb239-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_A<span class="fl">.1</span> <span class="sc">~</span> V8 <span class="sc">/</span> <span class="fu">sqrt</span>(V7 <span class="sc">*</span> V9))</span></code></pre></div>
<pre><code>##        Estimate        SE
## r_A.1 0.8281977 0.1723661</code></pre>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="asreml-biv.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_A<span class="fl">.2</span> <span class="sc">~</span> V11 <span class="sc">/</span> <span class="fu">sqrt</span>(V10 <span class="sc">*</span> V12))</span></code></pre></div>
<pre><code>##        Estimate        SE
## r_A.2 0.9642258 0.1241699</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="asreml-biv.html#cb243-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_res<span class="fl">.1</span> <span class="sc">~</span> V15 <span class="sc">/</span> <span class="fu">sqrt</span>(V14 <span class="sc">*</span> V16))</span></code></pre></div>
<pre><code>##          Estimate        SE
## r_res.1 0.7938392 0.0789263</code></pre>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="asreml-biv.html#cb245-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, r_res<span class="fl">.2</span> <span class="sc">~</span> V19 <span class="sc">/</span> <span class="fu">sqrt</span>(V18 <span class="sc">*</span> V20))</span></code></pre></div>
<pre><code>##          Estimate        SE
## r_res.2 0.6341139 0.1894661</code></pre>
<p>and the heritability too:</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="asreml-biv.html#cb247-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, h2.bwt<span class="fl">.1</span> <span class="sc">~</span> V7 <span class="sc">/</span> (V1 <span class="sc">+</span> V4 <span class="sc">+</span> V7 <span class="sc">+</span> V14))</span></code></pre></div>
<pre><code>##           Estimate         SE
## h2.bwt.1 0.2246746 0.09176899</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="asreml-biv.html#cb249-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, h2.bwt<span class="fl">.2</span> <span class="sc">~</span> V10 <span class="sc">/</span> (V1 <span class="sc">+</span> V4 <span class="sc">+</span> V10 <span class="sc">+</span> V18))</span></code></pre></div>
<pre><code>##           Estimate        SE
## h2.bwt.2 0.3119317 0.1442501</code></pre>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="asreml-biv.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, h2.tarsus<span class="fl">.1</span> <span class="sc">~</span> V9 <span class="sc">/</span> (V3 <span class="sc">+</span> V6 <span class="sc">+</span> V9 <span class="sc">+</span> V16))</span></code></pre></div>
<pre><code>##             Estimate        SE
## h2.tarsus.1 0.214216 0.1070477</code></pre>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="asreml-biv.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vpredict</span>(model_sex, h2.tarsus<span class="fl">.2</span> <span class="sc">~</span> V12 <span class="sc">/</span> (V3 <span class="sc">+</span> V6 <span class="sc">+</span> V12 <span class="sc">+</span> V20))</span></code></pre></div>
<pre><code>##              Estimate        SE
## h2.tarsus.2 0.4492118 0.1833703</code></pre>
<p>Now we can look at the fixed effects parameters and assess their significance with a conditional Wald F-test:</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="asreml-biv.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_sex, <span class="at">coef =</span> <span class="cn">TRUE</span>)<span class="sc">$</span>coef.fi</span>
<span id="cb255-2"><a href="asreml-biv.html#cb255-2" aria-hidden="true" tabindex="-1"></a><span class="fu">wald.asreml</span>(model_sex, <span class="at">denDF =</span> <span class="st">&quot;default&quot;</span>, <span class="at">ssType =</span> <span class="st">&quot;conditional&quot;</span>)<span class="sc">$</span>Wald</span></code></pre></div>
<pre><code>##                            solution std error    z.ratio
## at(trait, tarsus):sex_1  0.00000000        NA         NA
## at(trait, tarsus):sex_2 -0.05549717 0.4758546 -0.1166263
## at(trait, bwt):sex_1     0.00000000        NA         NA
## at(trait, bwt):sex_2     1.93936200 0.1903213 10.1899393
## trait_bwt                6.37791872 0.2311775 27.5888427
## trait_tarsus            20.58389296 0.4942600 41.6458836</code></pre>
<pre><code>## Multi-section model using the sigma parameterization.
## ASReml 4.1.0 Fri May 21 10:23:00 2021
##           LogLik        Sigma2     DF     wall    cpu
##  1     -2388.736           1.0   1807 10:23:01    0.1
##  2     -2388.736           1.0   1807 10:23:01    0.1
## Calculating denominator DF</code></pre>
<pre><code>## 
##                       Df denDF   F.inc   F.con Margin      Pr
## trait                  2  44.8 1522.00 1522.00        0.00000
## at(trait, bwt):sex     1 137.5  220.90  103.80      B 0.00000
## at(trait, tarsus):sex  1 138.6    0.01    0.01      B 0.90737</code></pre>
<!--  what do I need to add ?  comparison model partitionn and not !
  how to change parameter, already done with reduced model part ! 
  cov betweem random effect?? but meed to fix the univ part first -->

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scenario-and-data-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="gremlin-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/JulienGAMartin/wam_tuto/03_01-biv_asreml.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["wam_tuto.pdf", "wam_tuto.epub", "wam_tuto.mobi"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
},
"toc_depth": 4
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
